/**
 * PartThumbnail — inline render of the compact SVG the geometry engine
 * produced at analysis time (parts.thumbnail_svg). Server-safe.
 * File path: /components/viewer/part-thumbnail.tsx
 *
 * The SVG string is generated by lib/geometry/svg.ts geometryToSvg() on the
 * server from our own geometry — never from user-supplied markup — so
 * rendering it with dangerouslySetInnerHTML is safe. Falls back to an
 * empty dark box when a part has no geometry yet (manual/STEP stubs).
 */

type Props = {
  svg: string | null | undefined;
  /** Box size in px (square). Default 64. */
  size?: number;
  /** Accessible name — pass the part name from content/props. */
  label: string;
  className?: string;
};

export function PartThumbnail({ svg, size = 64, label, className = "" }: Props) {
  return (
    <div
      role="img"
      aria-label={label}
      className={`shrink-0 overflow-hidden bg-canvas [&>svg]:block [&>svg]:h-full [&>svg]:w-full ${className}`.trim()}
      style={{ width: size, height: size }}
      dangerouslySetInnerHTML={svg ? { __html: svg } : undefined}
    />
  );
}
