/**
 * admin content (EN) — mirror of /content/admin.ts (same keys, parity test).
 * File path: /content/en/admin.ts
 */

import type { AdminContent } from "@/content/admin";

export const admin: AdminContent = {
  title: "Admin",
  index: {
    eyebrow: "Admin",
    title: "Administration",
    subtitle: "Rate tables, machines, users, overrides and the audit log.",
    cards: {
      rates: {
        title: "Rate tables",
        body: "Versioned rate tables. Editing creates a new version; quotes keep the version they were priced with.",
        active: "Active version: {label}",
        noActive: "No active rate version — activate one.",
        placeholders: "{count} placeholder rows",
        open: "Open rate tables",
      },
      machines: {
        title: "Machines",
        body: "The machine park and its feasibility limits (data, not code).",
        count: "{count} machines",
        open: "Open machines",
      },
      overrides: {
        title: "Overrides",
        body: "Sales requests to override a feasibility rule.",
        pending: "{count} pending",
        open: "Open the queue",
      },
      users: {
        title: "Users",
        body: "Invitations, roles and interface language.",
        count: "{count} accounts",
        open: "Open users",
      },
      calculator: {
        title: "Machine-hour calculator",
        body: "Cost per machine hour from purchase price, depreciation, energy, gas, operator and overhead.",
        open: "Open calculator",
      },
      audit: {
        title: "Audit log",
        body: "Who changed what and when — rates, overrides, statuses, users.",
        open: "Open the log",
      },
      settings: {
        title: "Quoting settings",
        body: "Company data for the PDF, VAT rates, packaging, shipping, job setups, assembly labour and weld speeds.",
        open: "Open settings",
        placeholders: "{count} values to confirm",
        missing: "Tables missing — run the migration",
        confirmed: "Confirmed",
      },
    },
  },
  rates: {
    eyebrow: "Rate tables",
    title: "Rate versions",
    subtitle:
      "Rows of a version are immutable once it is active or used by a quote. Clone a version, edit the copy, activate it.",
    versions: {
      columns: {
        label: "Label",
        created: "Created",
        createdBy: "Author",
        status: "Status",
        usedBy: "Quotes",
        placeholders: "Placeholders",
        actions: "Actions",
      },
      statusActive: "Active",
      statusDraft: "Draft",
      statusUsed: "Used",
      current: {
        title: "Current prices",
        body: "Material and service prices of the active price list are edited directly — a change is saved to the database and applies from the next calculation. Versions are for bigger changes (clone, compare, activate).",
        materials: "Edit material prices",
        services: "Edit service rates",
        none: "No active price list — activate a version below.",
      },
      cloneTitle: "Clone this version",
      cloneLabel: "Label of the new version",
      cloneLabelPlaceholder: "e.g. v2 — calibrated rates",
      cloneSubmit: "Clone",
      activate: "Activate",
      activateQuestion: "Activate this version? New quotes will use these rates.",
      delete: "Delete",
      deleteQuestion: "Delete this version with all its rows?",
      deleteBlockedActive: "The active version cannot be deleted.",
      deleteBlockedUsed: "A version used by quotes cannot be deleted.",
      open: "Open",
      empty: "No rate versions",
      emptyBody: "Load the seed or create a version in the database.",
      notices: {
        cloned: "New version created. Edit the rows, then activate it.",
        activated: "The version is now active.",
        deleted: "The version was deleted.",
        cloneFailed: "Cloning the version failed.",
        activateFailed: "Activating the version failed.",
        activateMissing: "This version no longer exists — refresh the list and pick another one.",
        deleteFailed: "The version could not be deleted (active or used by quotes).",
        labelRequired: "Give the new version a label.",
      },
    },
    version: {
      eyebrow: "Rate version",
      backToList: "All versions",
      diffLink: "Diff against active",
      csvExport: "Export CSV",
      csvImport: "Import CSV",
      tabsLabel: "Rate tables",
      readOnlyActive:
        "This version is active — its rows are read-only. Clone it, edit the copy and activate the copy.",
      liveActive:
        "This is the active price list. A saved change applies to every new calculation at once; {drafts} open quotes re-price when opened; sent and decided quotes keep their prices.",
      readOnlyUsed:
        "This version has been used by quotes ({count}) — its rows are immutable. Clone it to edit.",
      cloneToEdit: "Clone to edit",
      cloneToEditLabel: "Label of the copy",
      cloneToEditSubmit: "Clone and open",
      meta: {
        created: "Created",
        createdBy: "Author",
        usedBy: "Used by quotes",
        placeholders: "Placeholder rows",
        status: "Status",
        note: "Note",
      },
      unknownTable: "Unknown rate table.",
    },
    tables: {
      general: "General",
      materials: "Materials",
      laser: "Laser",
      tube_laser: "Tube laser",
      bend: "Bending",
      roll: "Rolling",
      weld: "Welding",
      thread: "Threads",
      feature: "Features",
      finish: "Finishing",
      leadtime: "Lead time",
    },
    columns: {
      general: {
        machine_rate_eur_h: "Machine rate (€/h)",
        labour_rate_eur_h: "Labour rate (€/h)",
        machining_rate_eur_h: "Machining rate (€/h)",
        default_margin_pct: "Default margin (%)",
        margin_by_class: "Margin by customer class",
        blank_margin_mm: "Blank margin (mm)",
        slow_contour_factor: "Slow-contour factor",
        default_stitch_bead_mm: "Default stitch weld — bead (mm)",
        default_stitch_pitch_mm: "Default stitch weld — pitch (mm)",
        handling_mass_limit_kg: "Single-person mass limit (kg)",
        handling_surcharge_eur: "Handling surcharge (€/part)",
        weld_handling_per_part: "Welding-only handling (€/part)",
        pricing_mode: "Pricing mode",
        order_charge_eur: "Order charge (€)",
        packaging_box_eur: "Packaging — box (€)",
        packaging_pallet_eur: "Packaging — pallet (€)",
      },
      materials: {
        code: "Code",
        name: "Name",
        family: "Family",
        density_kg_m3: "Density (kg/m³)",
        rm_n_mm2: "Rm (N/mm²)",
        price_per_kg: "Price €/kg by thickness",
        sheet_formats: "Sheet formats",
        scrap_pct_default: "Default scrap (%)",
      },
      laser: {
        material_code: "Material",
        thickness_mm: "Thickness (mm)",
        in_house: "In-house",
        mode: "Mode",
        speed_m_min: "Speed (m/min)",
        pierce_s: "Pierce (s)",
        price_per_m: "Price (€/m)",
        price_per_pierce: "Price per pierce (€)",
        gas: "Gas",
        min_contour_mm: "Min. contour (mm)",
        supplier: "Supplier",
        setup_eur: "Setup (€ per material + thickness)",
      },
      tube_laser: {
        profile_family: "Profile",
        wall_mm: "Wall (mm)",
        price_per_m_cut: "Cut price (€/m)",
        handling_per_part: "Handling (€/part)",
        setup: "Setup (€)",
      },
      bend: {
        thickness_mm: "Thickness (mm)",
        length_class_mm: "Length class (mm)",
        price_per_bend: "Price per bend (€)",
        setup_per_part_type: "Setup per part type (€)",
        setup_per_bend_line_eur: "Setup per bend line (€)",
        price_per_bend_per_m: "Bend length extension (€/m beyond 200 mm)",
        benchmarked_max_length_mm: "Benchmarked bend length up to (mm)",
        family_multipliers: "Family multipliers",
        material_codes: "Materials",
      },
      roll: {
        thickness_mm: "Thickness (mm)",
        radius_class_mm: "Radius class (mm)",
        price_per_m: "Price (€/m)",
        setup: "Setup (€)",
      },
      weld: {
        process: "Process",
        bead_mm: "Bead (mm)",
        price_per_mm: "Price (€/mm)",
        setup: "Setup (€)",
        min_order: "Minimum order (€)",
      },
      thread: { size: "Size", price_each: "Price (€/each)", setup_per_line_eur: "Setup per line (€)", price_by_thickness: "Price by thickness (€/each)", material_codes: "Materials" },
      feature: {
        code: "Code",
        name: "Name",
        price_each: "Price (€/each)",
        setup_per_line_eur: "Setup per line (€)",
        material_codes: "Materials",
        min_thickness_mm: "Thickness from (mm)",
        max_thickness_mm: "Thickness to (mm)",
      },
      finish: {
        code: "Code",
        name: "Name",
        unit: "Unit",
        price: "Price (€/unit)",
        minimum: "Minimum (€)",
        setup_per_order_eur: "Setup per order (€)",
        setup_per_line_eur: "Setup per line (€)",
        min_part_mm: "Minimum part size (mm)",
        material_codes: "Materials",
        min_thickness_mm: "Thickness from (mm)",
        max_thickness_mm: "Thickness to (mm)",
        price_per_part_eur: "Price per piece (€)",
        min_lead_time_days: "Min. lead time (working days)",
        minimum_scope: "Minimum scope",
        tier_multiplier_applies: "Lead-time multiplier",
        limits: "Limits",
      },
      leadtime: { working_days: "Working days", multiplier: "Price multiplier" },
    },
    options: {
      mode: { time: "time", per_m: "per metre" },
      gas: { O2: "O₂", N2: "N₂", air: "air" },
      process: { mig_mag: "MIG/MAG", tig: "TIG", laser: "laser", mma: "MMA (stick)" },
      unit: { m2: "m²", kg: "kg", m: "m", each: "each", part: "per part" },
      family: {
        mild_steel: "mild steel",
        stainless: "stainless",
        aluminium: "aluminium",
        brass: "brass",
        copper: "copper",
      },
      profileFamily: { round: "round", square: "square", rectangular: "rectangular", open: "open" },
      pricingMode: { cost: "cost (rates + margin)", market: "market (selling prices)" },
    },
    grid: {
      addRow: "Add row",
      saveRow: "Save",
      deleteRow: "Delete",
      deleteRowQuestion: "Delete this row?",
      deleteMaterialQuestion: "Delete this material together with its laser rows ({count}) in this version?",
      revertRow: "Revert",
      saving: "Saving…",
      saved: "Row saved.",
      deleted: "Row deleted.",
      unsaved: "Unsaved changes",
      newRow: "New",
      keyboardHint: "Tab — next cell · Enter — save row · Esc — revert changes",
      noRows: "No rows in this table.",
      edit: "Edit",
      placeholderColumn: "Status",
      actionsColumn: "Actions",
      yes: "yes",
      no: "no",
      none: "—",
      readOnly: "Read-only",
      rowLabel: "Row {key}",
    },
    json: {
      apply: "Apply",
      cancel: "Cancel",
      add: "Add entry",
      remove: "Remove",
      empty: "No entries",
      bands: {
        title: "Price per kg by thickness",
        maxThickness: "Up to thickness (mm)",
        pricePerKg: "Price (€/kg)",
        summary: "{count} bands",
      },
      formats: {
        title: "Sheet formats",
        length: "Length (mm)",
        width: "Width (mm)",
        summary: "{count} formats",
      },
      margins: {
        title: "Margin by customer class",
        customerClass: "Customer class",
        marginPct: "Margin (%)",
        summary: "{count} classes",
        classPlaceholder: "e.g. key",
      },
    },
    csv: {
      title: "CSV import",
      help:
        "The first row is a header with the column names (as in the export). Rows are matched on their natural key: existing rows are updated, new ones added. Imported rows stop being placeholders.",
      helpColumns: "Columns: {columns}",
      file: "CSV file",
      submit: "Import",
      importing: "Importing…",
      imported: "Imported {count} rows.",
      errorsTitle: "Errors ({count})",
      lineError: "Line {line}: {message}",
      noFile: "Choose a CSV file.",
      tooLarge: "The file is too large (limit 2 MB).",
      emptyFile: "The file has no data rows.",
      missingColumns: "Header is missing columns: {columns}",
      download: "Download CSV",
      delimiterHint: "Delimiter: comma or semicolon (detected automatically).",
    },
    diff: {
      eyebrow: "Comparison",
      title: "Differences against the active version",
      subtitle: "Rows matched on their natural key (material code, material + thickness + in-house, profile + wall…).",
      backToVersion: "Back to the version",
      noActive: "No active version — nothing to compare against.",
      isActive: "This is the active version — a diff against itself has no differences.",
      added: "Added",
      removed: "Removed",
      changed: "Changed",
      unchanged: "unchanged",
      key: "Key",
      column: "Column",
      before: "Active",
      after: "This version",
      noChanges: "No differences in this table.",
      summary: "{added} added · {removed} removed · {changed} changed · {unchanged} unchanged",
    },
    errors: {
      forbidden: "Only an admin can change rate tables.",
      locked: "This version is locked for editing.",
      versionActive: "The active version is read-only — clone it.",
      versionHasQuotes: "A version used by quotes is immutable — clone it.",
      notFound: "Row or version not found.",
      validation: "Fix the highlighted cells.",
      db: "Database error: {message}",
      generic: "Something went wrong. Try again.",
      required: "Required",
      invalidNumber: "Invalid number",
      negative: "Must not be negative",
      invalidOption: "Invalid option",
      invalidJson: "Invalid JSON data",
      tooLong: "Too long",
      invalid: "Invalid value",
      duplicateKey: "A row with this key already exists.",
      noActiveVersion: "No active rate version.",
      unknownTable: "Unknown table.",
      keyChange: "The key of an existing row cannot change — add a new row instead.",
      marginTooHigh: "A margin must be below 100 % (price = cost ÷ (1 − margin)).",
      materialInUse:
        "This material has laser rows in this version ({count}) — refresh the page and confirm deleting them together.",
    },
  },
  sheet: {
    bendTable: {
      eyebrow: "STEP flat patterns",
      title: "Bend table",
      subtitle: "Bend allowances (BA) used to unfold STEP models. DIN 6935 rows are formula values — only a test bend clears the “bend deduction unverified” flag. A version used by a quote is frozen.",
      columns: { label: "Version", status: "Status", rows: "Rows", usedBy: "Used by quotes", created: "Created", actions: "Actions" },
      statusActive: "Active",
      statusDraft: "Draft",
      open: "Open",
      activate: "Activate",
      activateQuestion: "Activate this bend-table version? New STEP files will be unfolded with its allowances.",
      cloneTitle: "Clone to edit",
      cloneLabel: "Label of the new version",
      cloneSubmit: "Clone",
      empty: "No bend-table versions — run migration 20260928130000.",
      version: {
        eyebrow: "Bend table",
        backToList: "Back to the versions",
        title: "Version {label}",
        immutable: "This version is used by a quote and is immutable. Clone it to edit.",
        columns: { family: "Family", thickness: "Thickness (mm)", radius: "Inner radius (mm)", vDie: "Die V (mm)", angle: "Angle (°)", allowance: "Allowance BA (mm)", source: "Source", note: "Note", actions: "Actions" },
        sources: { din6935: "DIN 6935 (formula)", test_bend: "Test bend" },
        addTitle: "Add or correct a row (test bend)",
        addHelp: "Enter the allowance directly, or the test-bend result: the strip's flat length and the measured outside legs — BA = flat − leg A − leg B + 2·(r + t).",
        fields: { family: "Material family", thickness: "Thickness (mm)", radius: "Inner radius (mm)", vDie: "Die V (mm)", angle: "Bend angle (°)", allowance: "Allowance BA (mm)", flatLength: "Strip flat length (mm)", legA: "Leg A measured (mm)", legB: "Leg B measured (mm)", note: "Note" },
        computedHelp: "Leave BA empty to compute it from the measurement.",
        save: "Save row",
        delete: "Delete",
        deleteQuestion: "Delete this row?",
        empty: "No rows in this version.",
      },
      notices: { saved: "Row saved.", deleted: "Row deleted.", cloned: "Version cloned.", activated: "Version activated." },
    },
    tooling: {
      eyebrow: "Press brake",
      title: "Press-brake tooling",
      subtitle: "Punches (height, straight / gooseneck, tip radius, throat) and dies (V, minimum flange) for the DFM checks: flange too short and punch collision. Rows marked placeholder must be replaced with the real tools.",
      columns: { code: "Code", kind: "Kind", name: "Name", height: "Height (mm)", type: "Type", tipRadius: "Tip R (mm)", throat: "Throat (mm)", v: "V (mm)", minFlange: "Min. flange (mm)", placeholder: "Placeholder", actions: "Actions" },
      kinds: { punch: "Punch", die: "Die" },
      types: { straight: "straight", gooseneck: "gooseneck" },
      placeholderChip: "placeholder",
      addTitle: "Add or correct a tool",
      fields: { code: "Code", kind: "Kind", name: "Name", height: "Punch height (mm)", type: "Punch type", tipRadius: "Tip radius (mm)", throat: "Throat depth (mm)", v: "Die opening V (mm)", minFlange: "Minimum flange (mm)" },
      save: "Save tool",
      delete: "Delete",
      deleteQuestion: "Delete this tool?",
      empty: "No tools — run migration 20260928130000.",
      notices: { saved: "Tool saved.", deleted: "Tool deleted." },
    },
    hardware: {
      eyebrow: "STEP models",
      title: "Hardware names",
      subtitle: "A substring of the PRODUCT name in a STEP file → hardware kind and size, and the rate feature code it is priced with. Without a feature code the line shows a red “not benchmarked” flag with the quantity.",
      columns: { pattern: "Name fragment", kind: "Kind", size: "Size", featureCode: "Feature code", note: "Note", actions: "Actions" },
      kinds: { weld_stud: "Weld stud", insert: "Press-in insert", unknown: "Unknown" },
      addTitle: "Add or correct a rule",
      addHelp: "Case-insensitive match, e.g. ACAO470ZP → insert M4 → insert_m4.",
      fields: { pattern: "Name fragment", kind: "Kind", size: "Size (e.g. M4, M3x8)", featureCode: "Feature code (rate_feature)", note: "Note" },
      save: "Save rule",
      delete: "Delete",
      deleteQuestion: "Delete this rule?",
      empty: "No rules.",
      notices: { saved: "Rule saved.", deleted: "Rule deleted." },
    },
    errors: {
      forbidden: "Only an administrator can change this.",
      validation: "Check the values in the form.",
      duplicate: "Such a row already exists.",
      versionUsed: "This version is used by a quote and is immutable — clone it.",
      notFound: "Row not found.",
      db: "Database error.",
    },
  },
  machines: {
    eyebrow: "Machines",
    title: "Machine park",
    subtitle: "Every machine's feasibility limits as data — the engine rules read them from here.",
    columns: { code: "Code", name: "Name", kind: "Kind", updated: "Updated", limits: "Limits" },
    kinds: {
      flat_laser: "Flat-bed laser",
      tube_laser: "Tube laser",
      press_brake: "Press brake",
      roll: "Plate roll",
      weld: "Welding",
    },
    empty: "No machines in the database.",
    edit: {
      eyebrow: "Machine",
      backToList: "All machines",
      name: "Display name",
      sectionLimits: "Limits",
      sectionRaw: "Limits JSON",
      modeTyped: "Form",
      modeRaw: "Raw JSON",
      rawHelp: "Fallback view: the same object that goes into the limits column. Validated with the machine kind's schema.",
      rawLabel: "Limits (JSON)",
      save: "Save machine",
      saved: "Machine saved.",
      issuesTitle: "The limits failed validation",
      perFamily: "By material family",
      fields: {
        flat_laser: {
          bedLengthMm: "Bed length X (mm)",
          bedWidthMm: "Bed width Y (mm)",
          zMm: "Z range (mm)",
          edgeMarginMm: "Edge margin (mm)",
          maxThicknessMm: "Max. thickness (mm)",
        },
        tube_laser: {
          maxRoundDiameterMm: "Max. round diameter (mm)",
          maxRectSideMm: "Max. profile side (mm)",
          maxCircumscribedMm: "Max. circumscribed circle (mm)",
          maxLengthMm: "Max. length (mm)",
          maxKgPerM: "Max. mass (kg/m)",
          maxRawWeightKg: "Max. raw bar weight (kg)",
          wallThicknessMm: "Max. wall (mm)",
          modeA: "Mode A",
          modeB: "Mode B",
        },
        press_brake: {
          forceKN: "Force (kN)",
          bendLengthMm: "Bend length (mm)",
          betweenColumnsMm: "Width between columns (mm)",
          openHeightMm: "Open height (mm)",
          dieFactor: "Die factor V = k × t",
        },
        roll: {
          maxWidthMm: "Max. width (mm)",
          minRadiusMm: "Min. radius (mm)",
          maxThicknessMm: "Max. thickness (mm)",
        },
        weld: { processes: "Available welding processes" },
      },
      families: {
        mild_steel: "Mild steel",
        stainless: "Stainless",
        aluminium: "Aluminium",
        brass: "Brass",
        copper: "Copper",
      },
      processes: { mig_mag: "MIG/MAG", tig: "TIG", laser: "Laser welding", mma: "MMA (coated electrode)" },
    },
    errors: {
      forbidden: "Only an admin can change machines.",
      notFound: "Machine not found.",
      invalidJson: "Invalid JSON.",
      validation: "The limits failed validation.",
      db: "Database error: {message}",
      generic: "Something went wrong. Try again.",
      nameRequired: "The name is required.",
    },
  },
  calculator: {
    eyebrow: "Calculator",
    title: "Machine-hour cost",
    subtitle:
      "The spec section 13 model: depreciation, service, fixed costs, energy, gas, operator, tooling and overhead → cost per hour.",
    sectionInputs: "Inputs",
    sectionResult: "Result",
    storedHint: "Values are remembered in this browser (not in the database).",
    reset: "Clear",
    fields: {
      purchasePrice: "Purchase price (€)",
      residualValue: "Residual value (€)",
      usefulLifeYears: "Useful life (years)",
      productiveHoursPerYear: "Productive hours per year (h)",
      serviceEurPerYear: "Service (€/year)",
      otherFixedEurPerYear: "Other fixed costs (€/year)",
      powerKw: "Connected load (kW)",
      utilisationPct: "Power utilisation (%)",
      energyPriceEurPerKwh: "Energy price (€/kWh)",
      gasEurPerHour: "Gas (€/h)",
      operatorEurPerHour: "Operator cost (€/h)",
      operatorSharePct: "Operator share (%)",
      toolingEurPerYear: "Tooling (€/year)",
      overheadPct: "Overhead (%)",
    },
    help: {
      utilisation: "Share of the connected load actually drawn in production.",
      operatorShare: "How much of the operator's time goes to this machine (100 % = one operator full time).",
      overhead: "Percentage added on top of the sum of the other items (floor space, administration).",
      depreciation: "(purchase price − residual value) ÷ years ÷ hours.",
    },
    breakdown: {
      depreciation: "Depreciation",
      service: "Service",
      fixed: "Fixed costs",
      energy: "Energy",
      gas: "Gas",
      operator: "Operator",
      tooling: "Tooling",
      subtotal: "Subtotal",
      overhead: "Overhead",
      total: "Cost per hour",
    },
    perHour: "€/h",
    invalidInputs: "Enter positive productive hours and useful life to spread the yearly costs per hour.",
    useAsRate: {
      title: "Use as machine rate in a new rate version",
      body:
        "Clones the active version under the given label, writes the result into “Machine rate (€/h)” and opens the new version. Activation stays a separate step.",
      label: "Label of the new version",
      labelPlaceholder: "e.g. v2 — machine rate from the calculator",
      submit: "Create version",
      rateLabel: "Rate to store",
      noActiveVersion: "No active rate version to clone.",
      failed: "Creating the version failed.",
      forbidden: "Only an admin can create versions.",
      labelRequired: "Enter a label.",
      invalidRate: "The calculator result must be a positive number.",
    },
  },
  users: {
    eyebrow: "Users",
    title: "Accounts and roles",
    subtitle: "Admin edits rate tables and approves overrides, sales creates quotes, viewer only reads.",
    columns: { email: "E-mail", name: "Full name", role: "Role", locale: "Language", created: "Created", actions: "Actions" },
    you: "you",
    empty: "No users.",
    invite: {
      title: "Invite a user",
      body: "Sends an e-mail with an activation link. Role and language are set on the profile right away.",
      email: "E-mail",
      fullName: "Full name",
      role: "Role",
      locale: "Language",
      submit: "Send invitation",
      sent: "Invitation sent to {email}.",
      notConfigured:
        "Invitations are disabled: the Supabase service key (SUPABASE_SERVICE_ROLE_KEY) is missing on this environment.",
      errors: {
        invalidEmail: "Enter a valid e-mail address.",
        required: "Fill in the required fields.",
        forbidden: "Only an admin can invite users.",
        generic: "The invitation could not be sent.",
        exists: "A user with this e-mail already exists.",
        notConfigured: "Supabase service key missing — invitations are disabled.",
        roleNotSet: "The invitation was sent, but the role and language could not be saved — set them in the list below.",
      },
    },
    row: {
      save: "Save",
      saved: "User changes saved.",
      lastAdmin: "The last admin cannot lose the admin role.",
      forbidden: "Only an admin can change roles.",
      generic: "The changes could not be saved.",
      notFound: "User not found.",
      noChange: "Nothing changed.",
    },
  },
  overrides: {
    eyebrow: "Overrides",
    title: "Override queue",
    subtitle: "Requests to override a feasibility rule (amber flags). Approved ones lift the send block.",
    pending: { title: "Pending", empty: "No pending requests." },
    decided: {
      title: "Decided",
      empty: "No decided requests.",
      filters: {
        status: "Status",
        all: "All",
        approved: "Approved",
        rejected: "Rejected",
        search: "Search",
        searchPlaceholder: "Quote number, rule, note…",
        apply: "Filter",
        reset: "Clear",
      },
    },
    columns: {
      quote: "Quote",
      customer: "Customer",
      part: "Part",
      rule: "Rule",
      requester: "Requested by",
      note: "Justification",
      age: "Age",
      requested: "Requested",
      status: "Status",
      decidedBy: "Decided by",
      decidedAt: "Decided at",
      decisionNote: "Decision note",
      actions: "Decision",
    },
    decision: {
      note: "Decision note",
      notePlaceholder: "Conditions, remarks for sales…",
      approve: "Approve",
      reject: "Reject",
      approved: "Override approved.",
      rejected: "Override rejected.",
      quoteReverted: "The quote went back to Draft.",
    },
    status: { pending: "Pending", approved: "Approved", rejected: "Rejected" },
    age: { justNow: "just now", minutes: "{count} min", hours: "{count} h", days: "{count} d" },
    errors: {
      forbidden: "Only an admin decides overrides.",
      notFound: "Request not found.",
      alreadyDecided: "This request has already been decided.",
      noteRequired: "A rejection needs a note.",
      db: "Database error: {message}",
      generic: "The decision could not be saved.",
    },
    quoteVersion: "v{version}",
    unknownQuote: "(deleted quote)",
    unknownPart: "—",
    unknownUser: "(unknown)",
    wholeQuote: "whole quote",
  },
  audit: {
    eyebrow: "Log",
    title: "Audit log",
    subtitle: "Every rate change, override decision, status and role change — with the values before and after.",
    columns: { at: "When", actor: "Who", action: "Action", entity: "Entity", entityId: "Id", details: "Details" },
    filters: {
      entity: "Entity",
      action: "Action (prefix)",
      actionPlaceholder: "e.g. rate_ or override.",
      actor: "User",
      from: "From",
      to: "To",
      apply: "Filter",
      reset: "Clear",
      anyEntity: "All entities",
      anyActor: "Everyone",
    },
    details: { before: "Before", after: "After", none: "none", expand: "Show before/after" },
    empty: "No entries for these filters.",
    results: "{count} entries",
    system: "system",
    openEntity: "Open",
  },
  settings: {
    eyebrow: "Settings",
    title: "Quoting settings",
    subtitle: "Company data, VAT rates, packaging, shipping, job setups, welded-assembly labour and weld speeds. Non-versioned tables — a change applies from the next reprice of a quote.",
    nav: {
      company: "Company",
      vat: "VAT",
      packaging: "Packaging",
      shipping: "Shipping",
      setups: "Job setups",
      assembly: "Welded assemblies",
      weldSpeeds: "Weld speeds",
    },
    navLabel: "Settings tables",
    migrationMissing: "Table {table} does not exist in this database — run the migration supabase/migrations/20260930100000_assembly_mode.sql.",
    placeholderChip: "placeholder — confirm",
    confirmedChip: "confirmed",
    placeholderHint: "Rows marked “placeholder” are the calibration placeholders [CONFIRM] seeded by the migration. Save a row (even unchanged) to confirm its value — quotes then stop carrying the placeholder-rates flag.",
    overview: {
      columns: { table: "Table", rows: "Rows", placeholders: "To confirm", status: "Status", actions: "Actions" },
      open: "Open",
      statusMissing: "table missing",
      statusOk: "confirmed",
      statusPlaceholder: "{count} to confirm",
      singleRow: "1 row",
    },
    actions: { save: "Save", delete: "Delete", deleteQuestion: "Delete this row?", add: "Add row", cancel: "Cancel" },
    columns: { placeholder: "Status", updated: "Updated", actions: "Actions" },
    notices: { saved: "Saved.", deleted: "Row deleted." },
    errors: {
      forbidden: "Only an administrator can change settings.",
      validation: "Check the values in the form.",
      duplicate: "Such a row already exists (same key).",
      notFound: "Row not found — reload the page.",
      missingTable: "The table does not exist — run the migration 20260930100000_assembly_mode.sql.",
      db: "Database error.",
    },
    fieldPrefix: "Field: {field}",
    company: {
      title: "Company data",
      hint: "The sender block of the quote PDF (name, address, tax id, bank account), the OSS switch and the assembly margins. Values containing 000-000, PL00, XXXX or [CONFIRM] block the PDF export.",
      sections: { identity: "Company", address: "Address", contact: "Contact", registry: "Registers", bank: "Bank", pricing: "Pricing" },
      fields: {
        brand: "Brand (PDF header)",
        legal_name: "Legal name",
        street: "Street and number",
        postal_code: "Postal code",
        city: "City",
        country: "Country (ISO-2)",
        phone: "Phone",
        email: "E-mail",
        website: "Website",
        nip: "NIP (tax id)",
        regon: "REGON",
        krs: "KRS",
        bank_name: "Bank",
        iban_pln: "IBAN (PLN)",
        iban_eur: "IBAN (EUR)",
        swift: "SWIFT / BIC",
        oss_active: "OSS active (destination VAT for private customers in the EU)",
        assembly_margin_pct: "Minimum assembly margin (%)",
        subcontract_margin_pct: "Subcontract mark-up (%)",
      },
      ossHelp: "With OSS active a private (B2C) customer in another EU country gets the destination country's VAT rate from the VAT table; without OSS the Polish rate.",
      marginsHelp: "A welded assembly is priced with margin max(quote margin, this value) on revenue. The subcontract mark-up is added to the cost of forming done by a subcontractor. Range 0–90 %.",
      placeholderWarning: "The company data still holds placeholders: {fields}. Fill them in before sending a quote.",
    },
    vat: {
      title: "VAT rates",
      hint: "VAT rate by country: PL for domestic sales and for customers without a VAT id; the destination country for private EU customers when OSS is active. A customer with an EU VAT id outside Poland: 0 % (reverse charge).",
      columns: { country: "Country", rate: "VAT rate (%)" },
    },
    packaging: {
      title: "Packaging",
      hint: "The first row in position order whose limits (largest side, gross mass = net mass + 5 %) hold for the shipment — otherwise the last one. Charged once per quote.",
      columns: { code: "Code", name: "Name", maxSide: "Max side (mm)", maxMass: "Max mass (kg)", price: "Price (EUR)", position: "Position" },
    },
    shipping: {
      title: "Shipping",
      hint: "Weight bands per destination country: the first band with max kg ≥ the gross mass of the shipment. No row for the country → shipping must be entered manually on the quote.",
      columns: { country: "Country", maxKg: "Up to (kg)", price: "Price (EUR)", carrier: "Carrier", position: "Position" },
    },
    setups: {
      title: "Job setups",
      hint: "Setup cost charged ONCE per job and spread over the quantity: a laser nest per material/thickness pair, the press brake when any member is bent, the roll when rolled in-house, welding once per assembly type.",
      columns: { code: "Code", name: "Name", cost: "Cost (EUR)" },
      codes: {
        laser_nest: "Laser nest (per material / thickness)",
        press_brake: "Press-brake set-up",
        roll: "Plate-roll set-up",
        weld_fitup: "Welding and fit-up set-up (per assembly type)",
      },
    },
    assembly: {
      title: "Welded assemblies",
      hint: "Assembly labour: fit-up and deburring per part, tacks per piece, welding from the effective speeds, handling per assembly, step bending per hit, rolling per metre. Fit-up, tack and welding minutes × distortion factor → hours × labour rate; arc hours × gas and wire.",
      fields: {
        labour_rate_eur_h: "Labour rate (EUR/h)",
        gas_wire_eur_h: "Gas and wire (EUR per arc hour)",
        tack_seconds: "Tack (s each)",
        fitup_min_per_part: "Fit-up (min per part)",
        deburr_min_per_part: "Deburring (min per part)",
        handling_min_per_assembly: "Handling (min per assembly)",
        distortion_factor: "Distortion factor",
        step_bend_seconds_per_hit: "Step bending (s per hit)",
        roll_min_per_m: "Rolling (min per m)",
      },
      distortionHelp: "Multiplier for straightening and rework after welding (≥ 1), applied to fit-up, tacks and welding only.",
    },
    weldSpeeds: {
      title: "Weld speeds",
      hint: "EFFECTIVE speeds (including stops and repositioning) in mm/min by process and thickness. Lookup: rows of the process, the smallest thickness ≥ the seam thickness, otherwise the largest.",
      columns: { process: "Process", thickness: "Thickness (mm)", speed: "Speed (mm/min)" },
    },
  },
};
