/**
 * admin content (EN) — mirror of /content/admin.ts (same keys, parity test).
 * File path: /content/en/admin.ts
 */

import type { AdminContent } from "@/content/admin";

export const admin: AdminContent = {
  title: "Admin",
  index: {
    eyebrow: "Admin",
    title: "Administration",
    subtitle: "Rate tables, machines, users, overrides and the audit log.",
    cards: {
      rates: {
        title: "Rate tables",
        body: "Versioned rate tables. Editing creates a new version; quotes keep the version they were priced with.",
        active: "Active version: {label}",
        noActive: "No active rate version — activate one.",
        placeholders: "{count} placeholder rows",
        open: "Open rate tables",
      },
      machines: {
        title: "Machines",
        body: "The machine park and its feasibility limits (data, not code).",
        count: "{count} machines",
        open: "Open machines",
      },
      overrides: {
        title: "Overrides",
        body: "Sales requests to override a feasibility rule.",
        pending: "{count} pending",
        open: "Open the queue",
      },
      users: {
        title: "Users",
        body: "Invitations, roles and interface language.",
        count: "{count} accounts",
        open: "Open users",
      },
      calculator: {
        title: "Machine-hour calculator",
        body: "Cost per machine hour from purchase price, depreciation, energy, gas, operator and overhead.",
        open: "Open calculator",
      },
      audit: {
        title: "Audit log",
        body: "Who changed what and when — rates, overrides, statuses, users.",
        open: "Open the log",
      },
    },
  },
  rates: {
    eyebrow: "Rate tables",
    title: "Rate versions",
    subtitle:
      "Rows of a version are immutable once it is active or used by a quote. Clone a version, edit the copy, activate it.",
    versions: {
      columns: {
        label: "Label",
        created: "Created",
        createdBy: "Author",
        status: "Status",
        usedBy: "Quotes",
        placeholders: "Placeholders",
        actions: "Actions",
      },
      statusActive: "Active",
      statusDraft: "Draft",
      statusUsed: "Used",
      cloneTitle: "Clone this version",
      cloneLabel: "Label of the new version",
      cloneLabelPlaceholder: "e.g. v2 — calibrated rates",
      cloneSubmit: "Clone",
      activate: "Activate",
      activateQuestion: "Activate this version? New quotes will use these rates.",
      delete: "Delete",
      deleteQuestion: "Delete this version with all its rows?",
      deleteBlockedActive: "The active version cannot be deleted.",
      deleteBlockedUsed: "A version used by quotes cannot be deleted.",
      open: "Open",
      empty: "No rate versions",
      emptyBody: "Load the seed or create a version in the database.",
      notices: {
        cloned: "New version created. Edit the rows, then activate it.",
        activated: "The version is now active.",
        deleted: "The version was deleted.",
        cloneFailed: "Cloning the version failed.",
        activateFailed: "Activating the version failed.",
        activateMissing: "This version no longer exists — refresh the list and pick another one.",
        deleteFailed: "The version could not be deleted (active or used by quotes).",
        labelRequired: "Give the new version a label.",
      },
    },
    version: {
      eyebrow: "Rate version",
      backToList: "All versions",
      diffLink: "Diff against active",
      csvExport: "Export CSV",
      csvImport: "Import CSV",
      tabsLabel: "Rate tables",
      readOnlyActive:
        "This version is active — its rows are read-only. Clone it, edit the copy and activate the copy.",
      readOnlyUsed:
        "This version has been used by quotes ({count}) — its rows are immutable. Clone it to edit.",
      cloneToEdit: "Clone to edit",
      cloneToEditLabel: "Label of the copy",
      cloneToEditSubmit: "Clone and open",
      meta: {
        created: "Created",
        createdBy: "Author",
        usedBy: "Used by quotes",
        placeholders: "Placeholder rows",
        status: "Status",
        note: "Note",
      },
      unknownTable: "Unknown rate table.",
    },
    tables: {
      general: "General",
      materials: "Materials",
      laser: "Laser",
      tube_laser: "Tube laser",
      bend: "Bending",
      roll: "Rolling",
      weld: "Welding",
      thread: "Threads",
      feature: "Features",
      finish: "Finishing",
    },
    columns: {
      general: {
        machine_rate_eur_h: "Machine rate (€/h)",
        labour_rate_eur_h: "Labour rate (€/h)",
        machining_rate_eur_h: "Machining rate (€/h)",
        default_margin_pct: "Default margin (%)",
        margin_by_class: "Margin by customer class",
        blank_margin_mm: "Blank margin (mm)",
        slow_contour_factor: "Slow-contour factor",
        default_stitch_bead_mm: "Default stitch weld — bead (mm)",
        default_stitch_pitch_mm: "Default stitch weld — pitch (mm)",
        handling_mass_limit_kg: "Single-person mass limit (kg)",
        handling_surcharge_eur: "Handling surcharge (€/part)",
        weld_handling_per_part: "Welding-only handling (€/part)",
      },
      materials: {
        code: "Code",
        name: "Name",
        family: "Family",
        density_kg_m3: "Density (kg/m³)",
        rm_n_mm2: "Rm (N/mm²)",
        price_per_kg: "Price €/kg by thickness",
        sheet_formats: "Sheet formats",
        scrap_pct_default: "Default scrap (%)",
      },
      laser: {
        material_code: "Material",
        thickness_mm: "Thickness (mm)",
        in_house: "In-house",
        mode: "Mode",
        speed_m_min: "Speed (m/min)",
        pierce_s: "Pierce (s)",
        price_per_m: "Price (€/m)",
        price_per_pierce: "Price per pierce (€)",
        gas: "Gas",
        min_contour_mm: "Min. contour (mm)",
        supplier: "Supplier",
      },
      tube_laser: {
        profile_family: "Profile",
        wall_mm: "Wall (mm)",
        price_per_m_cut: "Cut price (€/m)",
        handling_per_part: "Handling (€/part)",
        setup: "Setup (€)",
      },
      bend: {
        thickness_mm: "Thickness (mm)",
        length_class_mm: "Length class (mm)",
        price_per_bend: "Price per bend (€)",
        setup_per_part_type: "Setup per part type (€)",
      },
      roll: {
        thickness_mm: "Thickness (mm)",
        radius_class_mm: "Radius class (mm)",
        price_per_m: "Price (€/m)",
        setup: "Setup (€)",
      },
      weld: {
        process: "Process",
        bead_mm: "Bead (mm)",
        price_per_mm: "Price (€/mm)",
        setup: "Setup (€)",
        min_order: "Minimum order (€)",
      },
      thread: { size: "Size", price_each: "Price (€/each)" },
      feature: { code: "Code", name: "Name", price_each: "Price (€/each)" },
      finish: {
        code: "Code",
        name: "Name",
        unit: "Unit",
        price: "Price (€/unit)",
        minimum: "Minimum (€)",
      },
    },
    options: {
      mode: { time: "time", per_m: "per metre" },
      gas: { O2: "O₂", N2: "N₂", air: "air" },
      process: { mig_mag: "MIG/MAG", tig: "TIG", laser: "laser", mma: "MMA (stick)" },
      unit: { m2: "m²", kg: "kg", m: "m", each: "each" },
      family: {
        mild_steel: "mild steel",
        stainless: "stainless",
        aluminium: "aluminium",
        brass: "brass",
        copper: "copper",
      },
      profileFamily: { round: "round", square: "square", rectangular: "rectangular", open: "open" },
    },
    grid: {
      addRow: "Add row",
      saveRow: "Save",
      deleteRow: "Delete",
      deleteRowQuestion: "Delete this row?",
      deleteMaterialQuestion: "Delete this material together with its laser rows ({count}) in this version?",
      revertRow: "Revert",
      saving: "Saving…",
      saved: "Row saved.",
      deleted: "Row deleted.",
      unsaved: "Unsaved changes",
      newRow: "New",
      keyboardHint: "Tab — next cell · Enter — save row · Esc — revert changes",
      noRows: "No rows in this table.",
      edit: "Edit",
      placeholderColumn: "Status",
      actionsColumn: "Actions",
      yes: "yes",
      no: "no",
      none: "—",
      readOnly: "Read-only",
      rowLabel: "Row {key}",
    },
    json: {
      apply: "Apply",
      cancel: "Cancel",
      add: "Add entry",
      remove: "Remove",
      empty: "No entries",
      bands: {
        title: "Price per kg by thickness",
        maxThickness: "Up to thickness (mm)",
        pricePerKg: "Price (€/kg)",
        summary: "{count} bands",
      },
      formats: {
        title: "Sheet formats",
        length: "Length (mm)",
        width: "Width (mm)",
        summary: "{count} formats",
      },
      margins: {
        title: "Margin by customer class",
        customerClass: "Customer class",
        marginPct: "Margin (%)",
        summary: "{count} classes",
        classPlaceholder: "e.g. key",
      },
    },
    csv: {
      title: "CSV import",
      help:
        "The first row is a header with the column names (as in the export). Rows are matched on their natural key: existing rows are updated, new ones added. Imported rows stop being placeholders.",
      helpColumns: "Columns: {columns}",
      file: "CSV file",
      submit: "Import",
      importing: "Importing…",
      imported: "Imported {count} rows.",
      errorsTitle: "Errors ({count})",
      lineError: "Line {line}: {message}",
      noFile: "Choose a CSV file.",
      tooLarge: "The file is too large (limit 2 MB).",
      emptyFile: "The file has no data rows.",
      missingColumns: "Header is missing columns: {columns}",
      download: "Download CSV",
      delimiterHint: "Delimiter: comma or semicolon (detected automatically).",
    },
    diff: {
      eyebrow: "Comparison",
      title: "Differences against the active version",
      subtitle: "Rows matched on their natural key (material code, material + thickness + in-house, profile + wall…).",
      backToVersion: "Back to the version",
      noActive: "No active version — nothing to compare against.",
      isActive: "This is the active version — a diff against itself has no differences.",
      added: "Added",
      removed: "Removed",
      changed: "Changed",
      unchanged: "unchanged",
      key: "Key",
      column: "Column",
      before: "Active",
      after: "This version",
      noChanges: "No differences in this table.",
      summary: "{added} added · {removed} removed · {changed} changed · {unchanged} unchanged",
    },
    errors: {
      forbidden: "Only an admin can change rate tables.",
      locked: "This version is locked for editing.",
      versionActive: "The active version is read-only — clone it.",
      versionHasQuotes: "A version used by quotes is immutable — clone it.",
      notFound: "Row or version not found.",
      validation: "Fix the highlighted cells.",
      db: "Database error: {message}",
      generic: "Something went wrong. Try again.",
      required: "Required",
      invalidNumber: "Invalid number",
      negative: "Must not be negative",
      invalidOption: "Invalid option",
      invalidJson: "Invalid JSON data",
      tooLong: "Too long",
      invalid: "Invalid value",
      duplicateKey: "A row with this key already exists.",
      noActiveVersion: "No active rate version.",
      unknownTable: "Unknown table.",
      keyChange: "The key of an existing row cannot change — add a new row instead.",
      marginTooHigh: "A margin must be below 100 % (price = cost ÷ (1 − margin)).",
      materialInUse:
        "This material has laser rows in this version ({count}) — refresh the page and confirm deleting them together.",
    },
  },
  machines: {
    eyebrow: "Machines",
    title: "Machine park",
    subtitle: "Every machine's feasibility limits as data — the engine rules read them from here.",
    columns: { code: "Code", name: "Name", kind: "Kind", updated: "Updated", limits: "Limits" },
    kinds: {
      flat_laser: "Flat-bed laser",
      tube_laser: "Tube laser",
      press_brake: "Press brake",
      roll: "Plate roll",
      weld: "Welding",
    },
    empty: "No machines in the database.",
    edit: {
      eyebrow: "Machine",
      backToList: "All machines",
      name: "Display name",
      sectionLimits: "Limits",
      sectionRaw: "Limits JSON",
      modeTyped: "Form",
      modeRaw: "Raw JSON",
      rawHelp: "Fallback view: the same object that goes into the limits column. Validated with the machine kind's schema.",
      rawLabel: "Limits (JSON)",
      save: "Save machine",
      saved: "Machine saved.",
      issuesTitle: "The limits failed validation",
      perFamily: "By material family",
      fields: {
        flat_laser: {
          bedLengthMm: "Bed length X (mm)",
          bedWidthMm: "Bed width Y (mm)",
          zMm: "Z range (mm)",
          edgeMarginMm: "Edge margin (mm)",
          maxThicknessMm: "Max. thickness (mm)",
        },
        tube_laser: {
          maxRoundDiameterMm: "Max. round diameter (mm)",
          maxRectSideMm: "Max. profile side (mm)",
          maxCircumscribedMm: "Max. circumscribed circle (mm)",
          maxLengthMm: "Max. length (mm)",
          maxKgPerM: "Max. mass (kg/m)",
          maxRawWeightKg: "Max. raw bar weight (kg)",
          wallThicknessMm: "Max. wall (mm)",
          modeA: "Mode A",
          modeB: "Mode B",
        },
        press_brake: {
          forceKN: "Force (kN)",
          bendLengthMm: "Bend length (mm)",
          betweenColumnsMm: "Width between columns (mm)",
          openHeightMm: "Open height (mm)",
          dieFactor: "Die factor V = k × t",
        },
        roll: {
          maxWidthMm: "Max. width (mm)",
          minRadiusMm: "Min. radius (mm)",
          maxThicknessMm: "Max. thickness (mm)",
        },
        weld: { processes: "Available welding processes" },
      },
      families: {
        mild_steel: "Mild steel",
        stainless: "Stainless",
        aluminium: "Aluminium",
        brass: "Brass",
        copper: "Copper",
      },
      processes: { mig_mag: "MIG/MAG", tig: "TIG", laser: "Laser welding", mma: "MMA (coated electrode)" },
    },
    errors: {
      forbidden: "Only an admin can change machines.",
      notFound: "Machine not found.",
      invalidJson: "Invalid JSON.",
      validation: "The limits failed validation.",
      db: "Database error: {message}",
      generic: "Something went wrong. Try again.",
      nameRequired: "The name is required.",
    },
  },
  calculator: {
    eyebrow: "Calculator",
    title: "Machine-hour cost",
    subtitle:
      "The spec section 13 model: depreciation, service, fixed costs, energy, gas, operator, tooling and overhead → cost per hour.",
    sectionInputs: "Inputs",
    sectionResult: "Result",
    storedHint: "Values are remembered in this browser (not in the database).",
    reset: "Clear",
    fields: {
      purchasePrice: "Purchase price (€)",
      residualValue: "Residual value (€)",
      usefulLifeYears: "Useful life (years)",
      productiveHoursPerYear: "Productive hours per year (h)",
      serviceEurPerYear: "Service (€/year)",
      otherFixedEurPerYear: "Other fixed costs (€/year)",
      powerKw: "Connected load (kW)",
      utilisationPct: "Power utilisation (%)",
      energyPriceEurPerKwh: "Energy price (€/kWh)",
      gasEurPerHour: "Gas (€/h)",
      operatorEurPerHour: "Operator cost (€/h)",
      operatorSharePct: "Operator share (%)",
      toolingEurPerYear: "Tooling (€/year)",
      overheadPct: "Overhead (%)",
    },
    help: {
      utilisation: "Share of the connected load actually drawn in production.",
      operatorShare: "How much of the operator's time goes to this machine (100 % = one operator full time).",
      overhead: "Percentage added on top of the sum of the other items (floor space, administration).",
      depreciation: "(purchase price − residual value) ÷ years ÷ hours.",
    },
    breakdown: {
      depreciation: "Depreciation",
      service: "Service",
      fixed: "Fixed costs",
      energy: "Energy",
      gas: "Gas",
      operator: "Operator",
      tooling: "Tooling",
      subtotal: "Subtotal",
      overhead: "Overhead",
      total: "Cost per hour",
    },
    perHour: "€/h",
    invalidInputs: "Enter positive productive hours and useful life to spread the yearly costs per hour.",
    useAsRate: {
      title: "Use as machine rate in a new rate version",
      body:
        "Clones the active version under the given label, writes the result into “Machine rate (€/h)” and opens the new version. Activation stays a separate step.",
      label: "Label of the new version",
      labelPlaceholder: "e.g. v2 — machine rate from the calculator",
      submit: "Create version",
      rateLabel: "Rate to store",
      noActiveVersion: "No active rate version to clone.",
      failed: "Creating the version failed.",
      forbidden: "Only an admin can create versions.",
      labelRequired: "Enter a label.",
      invalidRate: "The calculator result must be a positive number.",
    },
  },
  users: {
    eyebrow: "Users",
    title: "Accounts and roles",
    subtitle: "Admin edits rate tables and approves overrides, sales creates quotes, viewer only reads.",
    columns: { email: "E-mail", name: "Full name", role: "Role", locale: "Language", created: "Created", actions: "Actions" },
    you: "you",
    empty: "No users.",
    invite: {
      title: "Invite a user",
      body: "Sends an e-mail with an activation link. Role and language are set on the profile right away.",
      email: "E-mail",
      fullName: "Full name",
      role: "Role",
      locale: "Language",
      submit: "Send invitation",
      sent: "Invitation sent to {email}.",
      notConfigured:
        "Invitations are disabled: the Supabase service key (SUPABASE_SERVICE_ROLE_KEY) is missing on this environment.",
      errors: {
        invalidEmail: "Enter a valid e-mail address.",
        required: "Fill in the required fields.",
        forbidden: "Only an admin can invite users.",
        generic: "The invitation could not be sent.",
        exists: "A user with this e-mail already exists.",
        notConfigured: "Supabase service key missing — invitations are disabled.",
        roleNotSet: "The invitation was sent, but the role and language could not be saved — set them in the list below.",
      },
    },
    row: {
      save: "Save",
      saved: "User changes saved.",
      lastAdmin: "The last admin cannot lose the admin role.",
      forbidden: "Only an admin can change roles.",
      generic: "The changes could not be saved.",
      notFound: "User not found.",
      noChange: "Nothing changed.",
    },
  },
  overrides: {
    eyebrow: "Overrides",
    title: "Override queue",
    subtitle: "Requests to override a feasibility rule (amber flags). Approved ones lift the send block.",
    pending: { title: "Pending", empty: "No pending requests." },
    decided: {
      title: "Decided",
      empty: "No decided requests.",
      filters: {
        status: "Status",
        all: "All",
        approved: "Approved",
        rejected: "Rejected",
        search: "Search",
        searchPlaceholder: "Quote number, rule, note…",
        apply: "Filter",
        reset: "Clear",
      },
    },
    columns: {
      quote: "Quote",
      customer: "Customer",
      part: "Part",
      rule: "Rule",
      requester: "Requested by",
      note: "Justification",
      age: "Age",
      requested: "Requested",
      status: "Status",
      decidedBy: "Decided by",
      decidedAt: "Decided at",
      decisionNote: "Decision note",
      actions: "Decision",
    },
    decision: {
      note: "Decision note",
      notePlaceholder: "Conditions, remarks for sales…",
      approve: "Approve",
      reject: "Reject",
      approved: "Override approved.",
      rejected: "Override rejected.",
      quoteReverted: "The quote went back to Draft.",
    },
    status: { pending: "Pending", approved: "Approved", rejected: "Rejected" },
    age: { justNow: "just now", minutes: "{count} min", hours: "{count} h", days: "{count} d" },
    errors: {
      forbidden: "Only an admin decides overrides.",
      notFound: "Request not found.",
      alreadyDecided: "This request has already been decided.",
      noteRequired: "A rejection needs a note.",
      db: "Database error: {message}",
      generic: "The decision could not be saved.",
    },
    quoteVersion: "v{version}",
    unknownQuote: "(deleted quote)",
    unknownPart: "—",
    unknownUser: "(unknown)",
    wholeQuote: "whole quote",
  },
  audit: {
    eyebrow: "Log",
    title: "Audit log",
    subtitle: "Every rate change, override decision, status and role change — with the values before and after.",
    columns: { at: "When", actor: "Who", action: "Action", entity: "Entity", entityId: "Id", details: "Details" },
    filters: {
      entity: "Entity",
      action: "Action (prefix)",
      actionPlaceholder: "e.g. rate_ or override.",
      actor: "User",
      from: "From",
      to: "To",
      apply: "Filter",
      reset: "Clear",
      anyEntity: "All entities",
      anyActor: "Everyone",
    },
    details: { before: "Before", after: "After", none: "none", expand: "Show before/after" },
    empty: "No entries for these filters.",
    results: "{count} entries",
    system: "system",
    openEntity: "Open",
  },
};
