/**
 * Common chrome content (EN) — mirror of /content/common.ts.
 * File path: /content/en/common.ts
 */

import type { CommonContent } from "@/content/common";

export const common: CommonContent = {
  app: {
    name: "StretchMetal Quote",
    logoAria: "StretchMetal Quote — home",
    skipToContent: "Skip to content",
    mainNav: "Main navigation",
  },
  nav: {
    quotes: "Quotes",
    newQuote: "New quote",
    upload: "Upload files",
    customers: "Customers",
    guide: "Export guide",
    admin: "Administration",
    rates: "Rate tables",
    machines: "Machines",
    calculator: "Machine-hour calculator",
    users: "Users",
    overrides: "Overrides",
    audit: "Audit log",
    signOut: "Sign out",
    groupWork: "Work",
    groupAdmin: "Administration",
  },
  roles: { admin: "Administrator", sales: "Sales", viewer: "Viewer" },
  locales: { pl: "Polski", en: "English" },
  actions: {
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    create: "Create",
    close: "Close",
    confirm: "Confirm",
    back: "Back",
    next: "Next",
    search: "Search",
    download: "Download",
    upload: "Upload",
    apply: "Apply",
    reset: "Reset",
    duplicate: "Duplicate",
    export: "Export",
    import: "Import",
    add: "Add",
    remove: "Remove",
    yes: "Yes",
    no: "No",
    loading: "Loading…",
    saving: "Saving…",
    saved: "Saved",
    retry: "Retry",
    more: "More",
    less: "Less",
    none: "None",
    select: "Select",
    all: "All",
  },
  status: {
    draft: "Draft",
    pending_override: "Pending override",
    sent: "Sent",
    won: "Won",
    lost: "Lost",
  },
  severity: { green: "OK", amber: "Warning", red: "Blocked" },
  units: {
    mm: "mm",
    m: "m",
    mm2: "mm²",
    m2: "m²",
    kg: "kg",
    min: "min",
    pcs: "pcs",
    each: "each",
    bend: "bend",
    pierce: "pierce",
    h: "h",
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    notFound: "Page not found.",
    forbidden: "No access",
    forbiddenBody:
      "Your account cannot open this section. Ask an administrator.",
    unauthenticated: "Sign in to continue.",
    supabaseNotConfigured:
      "Supabase is not configured — set the environment variables (see README).",
    validation: "Check the highlighted fields.",
    network: "Connection error. Check your network and try again.",
  },
  login: {
    title: "Sign in",
    lead: "StretchMetal quoting tool. Staff access only.",
    email: "E-mail",
    password: "Password",
    submit: "Sign in",
    magicLink: "Send sign-in link",
    magicLinkSent: "A sign-in link has been sent to that address.",
    invalid: "Invalid e-mail or password.",
    forgot: "Forgot your password?",
    help: "Accounts are created by an administrator under Users.",
  },
  placeholder: {
    badge: "Placeholder",
    tooltip:
      "This rate is a placeholder [CONFIRM] — edit it to confirm the value.",
  },
  empty: {
    quotes: "No quotes yet. Create the first one.",
    parts: "No parts. Upload a DXF or add a part manually.",
    customers: "No customers.",
    generic: "No data.",
  },
  table: {
    rowsPerPage: "Rows per page",
    of: "of",
    noResults: "No results.",
  },
};
