/**
 * quote content (EN) — mirror of /content/quote.ts.
 * File path: /content/en/quote.ts
 */

import type { QuoteBuilderContent, QuoteContent } from "@/content/quote";


const builderEn: QuoteBuilderContent = {
  list: {
    eyebrow: "Work",
    title: "Quotes",
    subtitle: "Every offer: drafts, waiting for an override, sent and decided.",
    newQuote: "New quote",
    search: "Search quotes",
    searchPlaceholder: "Number or customer…",
    filterStatus: "Status",
    filterCustomer: "Customer",
    allStatuses: "All statuses",
    allCustomers: "All customers",
    columns: {
      number: "Number",
      customer: "Customer",
      type: "Type",
      status: "Status",
      parts: "Parts",
      total: "Net total",
      flags: "Flags",
      updated: "Updated",
      owner: "Owner",
    },
    empty: "No quotes",
    emptyBody: "Create the first quote or upload DXF files — a draft is created automatically.",
    noResults: "No quote matches the filters.",
    noFlags: "No flags",
    pendingOverrides: "{count} pending overrides",
  },
  create: {
    eyebrow: "Quote",
    title: "New quote",
    subtitle: "Quote header. Parts are added in the next step (file upload).",
    type: "Quote type",
    customer: "Customer",
    noCustomer: "No customer (fill in later)",
    currency: "Currency",
    currencyHelp: "PLN for Poland, EUR for every other country by default — editable.",
    fxRate: "EUR → PLN rate",
    fxRateHelp: "Rate tables are in EUR; the rate is stored on the quote and never changes by itself.",
    margin: "Margin (% of price)",
    marginHelp: "Default from the active rate version (or the customer class). Margin on price.",
    validityDays: "Validity (days)",
    leadTime: "Lead time",
    paymentTerms: "Payment terms",
    notes: "Internal notes",
    submit: "Create quote",
    cancel: "Cancel",
  },
  types: { fabrication: "Fabrication", welding_only: "Welding only" },
  header: {
    eyebrow: "Quote",
    version: "version {version}",
    created: "Created",
    sent: "Sent",
    rateVersion: "Rate version",
    noRateVersion: "pinned at the first pricing run",
    customer: "Customer",
    noCustomer: "— no customer —",
    currency: "Currency",
    fxRate: "EUR→PLN rate",
    fxRateHelp: "Rate tables are in EUR — the rate converts prices to PLN. Default rate: {fx}.",
    margin: "Margin (%)",
    markup: "markup {markup}",
    validityDays: "Validity (days)",
    validUntil: "valid until {date}",
    leadTime: "Lead time",
    leadTimeDays: "Lead time (working days)",
    leadTimeDaysHelp: "Promised lead time — on a market rate version it drives the price multiplier.",
    costVersion: "Cost version",
    marginMarketHelp:
      "Market rate version: benchmarked prices are selling prices. This margin prices only what the version does not benchmark (e.g. welding) from the cost rates; the margin in the summary comes from the comparison with the cost version.",
    paymentTerms: "Payment terms",
    notes: "Internal notes",
    showOperationsOnPdf: "Show operations on the PDF",
    weldingSeparate: "Welding as a separate block",
    save: "Save header",
    saved: "Header saved, prices recalculated.",
    readOnly: "Read only — this quote belongs to another user.",
    locked: "This quote has been sent — header and parts are locked. Create a new version to change it.",
    staleRates: "The stored prices were computed with other inputs than the ones saved on this quote (rate version, margin, lead time or currency) — recalculating on the server…",
    kind: "Quote kind",
    kindParts: "Part list",
    kindAssembly: "Welded assembly",
    kindHelp: "Welded assembly: parts are priced at cost inside the assembly, seams once per joint, setups once per job. A quote with at least one assembly is an assembly quote.",
    customerReference: "Customer inquiry no.",
    customerReferenceHelp: "The customer's inquiry number / reference — printed on the quote.",
    contactPerson: "Contact person",
    contactPersonHelp: "Defaults from the customer record; editable for this quote.",
    customerTypeHint: "Customer type: {type}",
  },
  parts: {
    title: "Parts",
    columns: {
      thumbnail: "Drawing",
      name: "Part",
      material: "Material / thickness",
      qty: "Qty",
      unitCost: "Cost / pc",
      unitPrice: "Price / pc",
      batch: "Batch total",
      flags: "Flags",
    },
    empty: "No parts",
    emptyBody: "Upload DXF or PDF files or add a part manually.",
    uploadParts: "Upload parts",
    openPart: "Open part",
    breakdown: "Operation breakdown",
    hideBreakdown: "Hide operations",
    extras: "Extras",
    remove: "Remove from quote",
    removeConfirm: "Remove this item? The part is deleted with it.",
    moveUp: "Move up",
    moveDown: "Move down",
    unattached: "Parts outside the quote",
    addToQuote: "Add to quote",
    noGeometry: "no geometry",
    scrap: "Scrap %",
    scrapDefault: "default",
    itemNotes: "Item notes",
    thumbnailAlt: "Thumbnail of part {name}",
  },
  operations: {
    title: "Operations",
    columns: {
      operation: "Operation",
      driver: "Qty / unit",
      rate: "Rate",
      unitCost: "Cost / pc",
      setupShare: "incl. setup",
      batchCost: "Batch cost",
    },
    types: {
      laser_cut: "Laser cutting",
      subcontract_cutting: "Cutting — subcontracted",
      tube_cut: "Tube / profile cutting",
      material: "Material",
      bend: "Bending",
      roll: "Rolling",
      weld: "Welding",
      thread: "Threads",
      feature: "Hole features",
      machining: "Machining",
      finish_powder: "Powder coating",
      finish_zinc: "Zinc plating",
      finish_deburr: "Deburring",
      finish_other: "Finish — other",
      engrave: "Engraving",
      handling: "Handling",
      setup: "Setup",
      other: "Other",
      order: "Order charge",
      packaging: "Packaging",
      shipping: "Shipping",
      leadtime: "Lead time",
    },
    labels: {
      laser_cut: "Laser cutting",
      subcontract_cutting: "Subcontracted cutting",
      material: "Material (sheet)",
      material_tube: "Material (profile)",
      bend: "Bend",
      bend_setup: "Setup — bending",
      roll: "Rolling",
      weld: "Weld seam",
      weld_setup: "Setup — welding",
      weld_handling: "Handling — welding",
      weld_min_order: "Minimum order — welding",
      thread: "Thread",
      machining: "Machining",
      engrave: "Engraving",
      tube_cut: "Profile cutting",
      handling: "Handling",
      laser_setup: "Setup — cutting (material/thickness)",
      deburr_setup: "Setup — deburring",
      deburr: "Deburring (both sides)",
      order_charge: "Order charge (line share)",
      packaging_box: "Packaging — box",
      packaging_pallet: "Packaging — pallet",
      lead_time: "Lead time (multiplier)",
      finish_setup: "Setup — finish (per line)",
      thread_setup: "Setup — tapping (per line)",
      bend_line_setup: "Setup — bend lines",
      feature_setup: "Setup — hole features (per line)",
      finish_minimum: "Finish minimum top-up",
      packaging: "Packaging",
      shipping: "Shipping",
      assembly_parts: "Assembly parts (material and cutting at cost)",
      assembly_fitup: "Fit-up",
      assembly_tack: "Tacking",
      assembly_weld: "Seam welding",
      assembly_gas_wire: "Gas and wire",
      assembly_deburr: "Part deburring",
      assembly_handling: "Assembly handling",
      step_bend: "Step bending (press-brake hits)",
      roll_forming: "Rolling",
      subcontract_forming: "Subcontracted forming",
      setup_laser_nest: "Setup — laser nest (once per job)",
      setup_press_brake: "Setup — press brake (once per job)",
      setup_roll: "Setup — roll (once per job)",
      setup_weld_fitup: "Setup — welding station (once per job)",
      deburr_nonferrous: "Edge breaking (both sides, aluminium / stainless)",
      deburr_one_side: "Edge breaking (burr side)",
      edge_round: "Edge rounding (both sides)",
      powder: "Powder coating",
      zinc: "Electro zinc plating",
      hot_dip: "Hot-dip galvanising",
      cert31: "Material certificate 3.1",
    },
    units: {
      m: "m",
      mm: "mm",
      pierce: "pierces",
      kg: "kg",
      bend: "bends",
      min: "min",
      m2: "m²",
      each: "pcs",
      part: "parts",
      lot: "lot",
    },
    placeholderRate: "placeholder rate",
    manual: "manual",
  },
  totals: {
    title: "Summary",
    byType: "By operation type",
    columns: { type: "Operation", cost: "Cost", price: "Price" },
    subtotalCost: "Total cost",
    subtotalPrice: "Net total price",
    margin: "Margin",
    marginAmount: "Margin amount",
    internalOnly: "Cost and margin are internal — never printed on the PDF.",
    inEur: "in EUR",
    fxNote: "Amounts in {currency} at rate {fx}.",
    preview: "Preview",
    previewBody: "Prices recomputed locally from your edits. Save to let the server confirm them.",
    pricedAt: "Priced {date}",
    notPriced: "Not priced yet — add parts or seams.",
    recalculate: "Recalculate",
    placeholderRates: "Placeholder rates [CONFIRM] were used — the admin must confirm them.",
    marketNote: "Market rate version (selling prices). Cost per: {version}. Lead time {days} days → multiplier {multiplier}.",
    marginBelow: "Margin below the {minPct} threshold — the quote is blocked until decided.",
  },
  flags: {
    title: "Feasibility flags",
    none: "No flags — everything within the machine limits.",
    red: "Blocking",
    amber: "Need confirmation",
    green: "Information",
    redExplanation: "A red flag blocks sending and cannot be overridden. Change the part (material, thickness, bends) or subcontract it.",
    confirm: "Confirm",
    confirmed: "Confirmed",
    requestOverride: "Request override",
    overrideRequested: "Override waiting for the admin's decision",
    overrideApproved: "Override approved",
    overrideRejected: "Override rejected — fix the part or request again",
    partScope: "Part: {name}",
    quoteScope: "Whole quote",
    dialogTitle: "Override request",
    dialogNote: "Justification for the admin",
    dialogNotePlaceholder: "Why we can do this despite the flag…",
    dialogSubmit: "Send request",
    dialogCancel: "Cancel",
    requestSent: "Override request sent. The quote waits for a decision.",
    confirmedToast: "Flag confirmed.",
  },
  overrides: {
    title: "Overrides",
    empty: "No overrides for this quote.",
    columns: {
      rule: "Rule",
      part: "Part",
      requestedBy: "Requested by",
      note: "Justification",
      status: "Status",
      decided: "Decision",
    },
    status: {
      pending: "Pending",
      approved: "Approved",
      rejected: "Rejected",
      confirmed: "Confirmed by sales",
    },
    confirmationNote: "confirmed by sales",
  },
  actions: {
    title: "Actions",
    upload: "Upload parts",
    duplicate: "New version",
    duplicateConfirm: "Create a new version of this quote (copy of parts and quantities, active rate version)?",
    duplicated: "New version created.",
    exportPdf: "PDF",
    exportPdfPl: "PDF (PL)",
    exportPdfEn: "PDF (EN)",
    withOperations: "with operations",
    withAssemblyParts: "with assembly parts list",
    send: "Send quote",
    sendConfirm: "Send the quote to the customer? The status becomes \"sent\".",
    sendBlocked: "Cannot send:",
    sent: "Quote e-mailed to the customer.",
    sentNoMail: "Quote marked as sent. PDF stored — e-mail sending is not configured, download the PDF and send it manually.",
    sentMailFailed: "Quote marked as sent, PDF stored — the e-mail failed to send. Download the PDF and send it manually.",
    pdfFailed: "The PDF could not be generated: {message}",
    mailNotConfigured: "E-mail sending is off (no Microsoft Graph configuration) — \"Send\" stores the PDF and changes the status.",
    markWon: "Won",
    markLost: "Lost",
    decisionSaved: "Status saved.",
    recalculate: "Recalculate prices",
    recalculated: "Prices recalculated on the server.",
    exportBlocked: "The PDF cannot be downloaded:",
  },
  send: {
    reasons: {
      red_flags: "the quote has red flags",
      pending_override: "an override is waiting for the admin's decision",
      amber_unconfirmed: "amber flags need a confirmation or an approved override",
      no_customer: "no customer",
      no_customer_email: "the customer has no e-mail address",
      no_items: "no parts and no seams",
      not_priced: "the quote has not been priced yet",
      customer_missing: "the customer has no name or address",
      customer_type_missing: "the customer type (B2B / B2C) is not set",
      company_placeholders: "the company settings still contain placeholder values",
      forming_unresolved: "a bend or roll is outside the machine park — pick step bending or subcontracting",
      status: "the quote was already sent or decided",
    },
    localePl: "Polish",
    localeEn: "English",
    sendLocale: "Quote language",
  },
  welding: {
    title: "Seams",
    partsCount: "Customer parts",
    partsCountHelp: "For handling: a cost per supplied part.",
    columns: {
      label: "Seam",
      process: "Process",
      bead: "Bead a [mm]",
      length: "Length [mm]",
      pattern: "Pattern",
      beadLength: "Segment [mm]",
      pitch: "Pitch [mm]",
      sides: "Sides",
      qty: "Qty",
    },
    patterns: { full: "full", stitch: "stitch" },
    processes: { mig_mag: "MIG/MAG", tig: "TIG", laser: "Laser", mma: "MMA (stick)" },
    addSeam: "Add seam",
    removeSeam: "Remove",
    importFromParts: "Import from drawings",
    importedNone: "The parts have no marked seams.",
    imported: "Imported {count} seams.",
    empty: "No seams. Add a row or import the seams marked on the drawings.",
    save: "Save seams",
    saved: "Seams saved, prices recalculated.",
    blockTitle: "Welding",
    minOrderApplied: "Minimum order applied.",
    seamDefaultLabel: "Seam {n}",
  },
  shipping: {
    title: "Shipping",
    enable: "Add shipping",
    disable: "Remove shipping",
    none: "No shipping (collection) — add it when the quote should include transport.",
    country: "Destination country",
    grossKg: "Gross mass [kg]",
    grossKgManual: "type it",
    grossKgComputed: "from parts and packaging",
    grossKgComputedValue: "computed: {kg} kg (parts + 5 % packaging)",
    grossKgUnknown: "computed after pricing",
    costSource: "Shipping cost",
    sourceManual: "manual",
    sourceTable: "from the carrier table",
    costEur: "Cost [EUR]",
    band: "Band: {carrier} · up to {maxKg} kg · {price}",
    noBand: "No band in the table for this country and mass — enter the cost manually.",
    noRates: "The shipping rate table is not loaded — enter the cost manually.",
    carrier: "Carrier",
    carrierFromBand: "from the table",
    extraLeadDays: "Extra transport days",
    extraLeadDaysHelp: "Days added to the lead time on the quote.",
  },
  priceScale: {
    title: "Price scale",
    enable: "Quote extra quantities",
    quantities: "Quantities",
    quantitiesHelp: "Whole numbers separated by commas, e.g. 20, 50, 100, 200, 500, 1000. Every item and assembly is priced at these quantities.",
    useDefaults: "Default set",
    invalid: "Invalid quantities: {values}",
    tooMany: "At most {max} quantities.",
    tableTitle: "Prices by quantity",
    columns: { subject: "Line", qty: "Qty", unitPrice: "Price / pc", total: "Total" },
    kinds: { item: "part", assembly: "assembly" },
    empty: "Save the header to compute the price scale.",
    noPrice: "—",
  },
  vat: {
    title: "Net / VAT / gross",
    net: "Net",
    shipping: "incl. shipping",
    rate: "VAT {rate}",
    amount: "VAT amount",
    gross: "Gross",
    countryNote: "rate of {country}",
    modes: {
      none: "No customer or country — VAT undetermined; net quote.",
      pl_domestic: "Customer in Poland — 23 % VAT.",
      b2c_domestic: "Customer without a VAT ID — the Polish 23 % rate applies.",
      b2c_oss: "Private customer in another EU country (OSS) — VAT of the destination country.",
      reverse_charge: "0 % VAT — intra-Community supply, reverse charge (WDT, art. 138 Directive 2006/112/EC).",
      export: "0 % VAT — export outside the EU.",
    },
    unknown: "VAT is determined once a customer with a B2B / B2C type is selected.",
  },
  assembly: {
    title: "Welded assemblies",
    add: "Add assembly",
    defaultName: "Assembly {n}",
    empty: "No assemblies",
    emptyBody: "Add an assembly, then move parts into it from the loose item list.",
    fields: {
      name: "Assembly name",
      drawingRef: "Drawing ref.",
      qty: "Assemblies",
      material: "Assembly material",
      materialNone: "— per part —",
      thickness: "Thickness [mm]",
      notes: "Notes",
    },
    save: "Save assembly",
    saved: "Assembly saved, prices recalculated.",
    created: "Assembly added.",
    remove: "Remove assembly",
    removeConfirm: "Remove this assembly? Its parts return to the loose list; its seams are deleted.",
    removed: "Assembly removed.",
    members: {
      title: "Assembly parts",
      columns: {
        part: "Part",
        qtyPerAssembly: "Pcs / assembly",
        orderQty: "Order qty",
        material: "Material",
        thickness: "Thickness",
        forming: "Forming",
      },
      empty: "The assembly has no parts yet — add them from the list below.",
      add: "Add parts",
      addPicker: "Loose item",
      addNone: "No loose items — upload parts to the quote.",
      addQty: "Pcs / assembly",
      remove: "Remove from assembly",
      removeConfirm: "Remove the part from the assembly? It returns to the loose list.",
      moved: "Part moved.",
      inherited: "per assembly",
      differs: "differs from the assembly",
    },
    material: {
      override: "Material differs from the assembly (deliberate)",
      overrideHelp: "Unchecked, the part inherits the assembly's material and thickness.",
      note: "Material note (printed on the quote)",
      noteHelp: "Required when DC01 is offered instead of S235.",
      noteRequired: "Enter a material note — DC01 replaces S235.",
      save: "Save material",
      saved: "Item material saved.",
    },
    seams: {
      title: "Assembly seams",
      add: "Add seam",
      edit: "Edit",
      remove: "Remove",
      save: "Save seam",
      cancel: "Cancel",
      unpair: "Count separately",
      added: "Seam added.",
      addedPaired: "Seam added as the second edge of the joint — not counted.",
      saved: "Seam saved.",
      removed: "Seam removed.",
      unpaired: "Seam counted separately.",
      empty: "No seams — add them here or mark edges in the part viewer (\"Add as assembly seam\").",
      byHand: "by hand",
      columns: {
        label: "Seam",
        part: "Part",
        length: "Length [mm]",
        process: "Process",
        thickness: "Thickness [mm]",
        type: "Type",
        pattern: "Parameters",
        sides: "Sides",
        counted: "Counted",
      },
      types: { continuous: "continuous", stitch: "stitch", tack: "tack" },
      paired: "= edge of {name}",
      pairedUnknown: "= neighbour's edge",
      notCounted: "not counted",
      countedYes: "yes",
      thicknessInherited: "per assembly",
      stitchInfo: "{bead} / {pitch} mm",
      tackInfo: "{count} tacks",
      beadMm: "Bead [mm]",
      pitchMm: "Pitch [mm]",
      tackCount: "Tack count",
      totals: {
        title: "Totals",
        counted: "Counted seams",
        paired: "skipped (second edge)",
        tacks: "Tacks",
        length: "Counted length",
        effective: "Effective length",
        byProcess: "By process",
        group: "{process} · {thickness} mm",
        groupNoThickness: "{process} · assembly thickness",
      },
      defaultLabel: "Seam {n}",
    },
    handoff: {
      add: "Add as assembly seam",
      pending: "Adding…",
      added: "added",
      paired: "paired with the neighbour's edge (not counted)",
      alreadyAdded: "already added",
      partOf: "Member of assembly: {name}",
      failed: "The seam could not be added.",
    },
    cost: {
      title: "Assembly cost and margin",
      adminOnly: "Admin only — never printed on the PDF.",
      columns: { line: "Line", minutes: "Minutes", amount: "Amount / assembly" },
      partsAtCost: "Parts at cost (material + cutting)",
      labour: "Labour",
      labourKinds: {
        fitup: "Fit-up",
        tack: "Tacking",
        weld: "Welding",
        gasWire: "Gas and wire",
        deburr: "Deburring",
        handling: "Handling",
        forming: "Forming",
      },
      totalMinutes: "Total minutes (after the distortion factor)",
      arcMinutes: "Arc time",
      setups: "Job setups (once per job)",
      setupsHelp: "spread over {qty} assemblies",
      subcontract: "Subcontracting",
      unitCost: "Cost / assembly",
      margin: "Margin applied",
      unitPrice: "Price / assembly",
      total: "Total",
      seamLength: "Counted seam length",
      notPriced: "The assembly has not been priced yet.",
      unpriceable: "The assembly cannot be priced — resolve the red flags (forming, missing rate).",
    },
    price: {
      unitPrice: "Price / assembly",
      total: "Total",
      qty: "{qty} pcs",
    },
  },
  forming: {
    title: "Forming",
    kinds: { roll: "Rolling", bend: "Bending" },
    fields: {
      insideRadiusMm: "Inside R [mm]",
      angleDeg: "Angle [°]",
      widthMm: "Width [mm]",
      bends: "Bends",
      lengthMm: "Bend length [mm]",
    },
    addRoll: "Add rolling",
    addBend: "Add bending",
    remove: "Remove",
    save: "Save forming",
    saved: "Forming saved, prices recalculated.",
    empty: "No forming operations.",
    resolution: {
      in_house: "in-house",
      step_bend: "step bending",
      subcontract: "subcontracted",
      none_needed: "no forming needed",
    },
    unresolved: "to be resolved",
    notFeasible: "Not feasible in-house — {reason}: {value} against the limit {limit}.",
    reasons: {
      min_radius: "radius below the roll minimum",
      max_thickness: "thickness above the roll limit",
      max_width: "width beyond the roll",
      bend_length: "bend length beyond the press brake",
      force: "bending force [kN] beyond the press brake",
      no_machine: "no such machine in the park",
      step_bend_hits: "the number of hits must be above zero",
    },
    stepBend: "Step bending",
    hits: "Press-brake hits",
    hitsHelp: "Suggestion: arc length ÷ 15 mm (R90 × 180° → 19).",
    applyStepBend: "Apply step bending",
    subcontract: "Subcontract",
    supplier: "Supplier",
    costEur: "Cost [EUR / pc]",
    extraLeadDays: "Extra days",
    applySubcontract: "Subcontract it",
    resolved: "Resolution saved, prices recalculated.",
    suspected: "The drawing suggests forming, but the part has no forming operation.",
    addForming: "Add forming",
    confirmNone: "Confirm: no forming needed",
    confirmedNone: "No forming confirmed.",
    noneNeeded: "no forming (confirmed)",
    rollSummary: "rolling {summary}",
    bendSummary: "bending {summary}",
  },
  extras: {
    title: "Extras — {name}",
    machining: "Machining",
    machiningMinutes: "Minutes per piece",
    features: "Hole features",
    featureCode: "Feature",
    featureCount: "Count",
    finish: "Finish",
    finishCode: "Finish",
    maskingMinutes: "Masking [min]",
    other: "Other line",
    otherLabel: "Label",
    otherCost: "Cost / pc [EUR]",
    handling: "Handling",
    handlingCost: "Cost / pc [EUR]",
    add: "Add",
    remove: "Remove",
    empty: "No extras — geometry-driven operations are priced automatically.",
    save: "Save extras",
    saved: "Extras saved, prices recalculated.",
    costEur: "Enter extra costs in EUR (the rate-table currency).",
    none: "none",
    summary: "{count} extras",
    notBenchmarked: "Not benchmarked — quote manually: {what}. Add an \"Other line\" with a lump sum.",
    colour: "Colour (RAL)",
    colourHelp: "One colour per line; the minimum is per colour.",
    unavailable: "not benchmarked for this material/thickness",
  },
  audit: {
    title: "Change history",
    empty: "No entries.",
    columns: { when: "When", who: "Who", action: "Event" },
    actions: {
      "quote.create": "quote created",
      "quote.update": "header changed",
      "quote.item.update": "item changed",
      "quote.item.remove": "item removed",
      "quote.item.add": "item added",
      "quote.item.reorder": "items reordered",
      "quote.welding.update": "seams changed",
      "quote.duplicate": "new version",
      "quote.reprice": "prices recalculated",
      "quote.send": "quote sent",
      "quote.status": "status changed",
      "override.request": "override requested",
      "override.confirm": "flag confirmed",
      "override.approve": "override approved",
      "override.reject": "override rejected",
      "assembly.create": "assembly added",
      "assembly.update": "assembly changed",
      "assembly.remove": "assembly removed",
      "quote.item.assembly": "part moved into / out of an assembly",
      "quote.item.material_override": "item material changed",
      "quote.item.forming": "forming changed",
      "forming.resolve": "forming resolved",
      "forming.confirm_none": "no forming confirmed",
      "seam.add": "seam added",
      "seam.update": "seam changed",
      "seam.remove": "seam removed",
      "seam.unpair": "seams unpaired",
    },
  },
  defaults: {
    // [CONFIRM] default payment terms text
    paymentTerms: "Payment by bank transfer within 14 days of the invoice date. Prices net, VAT according to applicable law.",
    // [CONFIRM] default lead time
    leadTime: "10–15 working days from order confirmation",
  },
  errors: {
    required: "Required.",
    invalid: "Invalid value.",
    tooLong: "Too long.",
    invalidNumber: "Invalid number.",
    invalidQty: "Quantity must be a whole number above zero.",
    invalidMargin: "Margin must be between 0 and 99.99 %.",
    invalidFx: "Invalid exchange rate.",
    invalidCurrency: "Pick PLN or EUR.",
    invalidType: "Pick a quote type.",
    invalidStatus: "Invalid status.",
    notFound: "Quote not found.",
    forbidden: "You are not allowed to change this quote.",
    locked: "The quote is locked (sent or decided).",
    noRates: "No active rate version — the admin must activate one.",
    pricing: "Pricing failed: {message}",
    config: "Server configuration error — the values were saved but the price was not computed: {message}",
    sendFailed: "Sending failed: {message}",
    cannotSend: "The quote does not meet the sending rules.",
    mail: "PDF stored, but the e-mail was not sent. Check the mail configuration.",
    generic: "Something went wrong. Try again.",
  },
};

export const quote: QuoteContent = {
  title: "Quote",
  builder: builderEn,
  customers: {
    eyebrow: "Customers",
    title: "Customers",
    subtitle: "Customer database: quote details, class and offer history.",
    newTitle: "New customer",
    newSubtitle: "The customer's country sets the default quote currency.",
    editEyebrow: "Customer",
    list: {
      search: "Search customers",
      searchPlaceholder: "Name, VAT id or e-mail…",
      newCustomer: "New customer",
      columns: {
        name: "Name",
        country: "Country",
        customerClass: "Class",
        customerType: "Type",
        vatId: "VAT id",
        email: "E-mail",
        quotes: "Quotes",
        lastQuote: "Last quote",
      },
      empty: "No customers",
      emptyBody: "Add the first customer to attach it to a quote.",
      noResults: "No customer matches the search.",
    },
    form: {
      sectionDetails: "Company",
      sectionContact: "Contact",
      sectionPreferences: "Preferences",
      name: "Name",
      vatId: "VAT id",
      vatIdHelp: "With the country prefix for EU companies, e.g. DE123456789. Outside Poland: 0 % VAT only with a VAT ID (reverse charge / export); Poland: always 23 %.",
      customerType: "Customer type",
      customerTypeHelp: "B2B — a company (VAT ID, reverse charge abroad, editable payment terms). B2C — a private person (gross prices on the quote, 100 % prepayment against a pro forma).",
      contactPerson: "Contact person",
      contactPersonHelp: "Default contact person on this customer's quotes.",
      requestedTerms: "Payment terms requested by the customer",
      requestedTermsHelp: "Recorded and printed on B2B quotes, e.g. \"30 days net, 2 % discount within 14 days\".",
      country: "Country",
      countryGroupPreferred: "Frequent countries",
      countryGroupOther: "Other countries",
      address: "Address",
      email: "E-mail",
      phone: "Phone",
      customerClass: "Customer class",
      preferredLocale: "Quote language",
      preferredLocaleNone: "Default (by country)",
      preferredLocaleHelp: "Language of the quote PDF and customer e-mails.",
      notes: "Notes",
      currencyHint: "Default quote currency: {currency} (PLN for Poland, EUR for every other country).",
      create: "Create customer",
      save: "Save changes",
      created: "Customer created.",
      saved: "Changes saved.",
      deleteCustomer: "Delete customer",
      deleteConfirm: "Delete this customer? Quotes stay but lose the link.",
      deleted: "Customer deleted.",
      backToList: "Customer list",
    },
    classes: {
      standard: "Standard",
      key: "Key account",
      new: "New",
      distributor: "Distributor",
    },
    types: {
      b2b: "B2B — company",
      b2c: "B2C — private person",
    },
    countries: {
      PL: "Poland",
      DE: "Germany",
      NL: "Netherlands",
      BE: "Belgium",
      CZ: "Czechia",
      SK: "Slovakia",
      AT: "Austria",
      FR: "France",
      IT: "Italy",
      ES: "Spain",
      GB: "United Kingdom",
      DK: "Denmark",
      SE: "Sweden",
      FI: "Finland",
      NO: "Norway",
      CH: "Switzerland",
      LT: "Lithuania",
      LV: "Latvia",
      EE: "Estonia",
      HU: "Hungary",
      RO: "Romania",
      UA: "Ukraine",
      LU: "Luxembourg",
      IE: "Ireland",
      PT: "Portugal",
      SI: "Slovenia",
      HR: "Croatia",
    },
    history: {
      title: "Quote history",
      empty: "This customer has no quotes yet.",
      columns: {
        number: "Number",
        version: "Version",
        type: "Type",
        status: "Status",
        date: "Date",
        total: "Total",
      },
      types: { fabrication: "Fabrication", welding_only: "Welding only" },
    },
    errors: {
      required: "Required.",
      tooLong: "Too long.",
      invalidEmail: "Invalid e-mail address.",
      invalidCountry: "Invalid country code (ISO 3166-1, e.g. DE).",
      invalidClass: "Pick a class from the list.",
      invalidLocale: "Pick a language from the list.",
      notFound: "Customer not found.",
      forbidden: "You are not allowed to do this.",
      generic: "The customer could not be saved. Try again.",
    },
  },
};
