/**
 * quote content (EN) — mirror of /content/quote.ts.
 * File path: /content/en/quote.ts
 */

import type { QuoteBuilderContent, QuoteContent } from "@/content/quote";


const builderEn: QuoteBuilderContent = {
  list: {
    eyebrow: "Work",
    title: "Quotes",
    subtitle: "Every offer: drafts, waiting for an override, sent and decided.",
    newQuote: "New quote",
    search: "Search quotes",
    searchPlaceholder: "Number or customer…",
    filterStatus: "Status",
    filterCustomer: "Customer",
    allStatuses: "All statuses",
    allCustomers: "All customers",
    columns: {
      number: "Number",
      customer: "Customer",
      type: "Type",
      status: "Status",
      parts: "Parts",
      total: "Net total",
      flags: "Flags",
      updated: "Updated",
      owner: "Owner",
    },
    empty: "No quotes",
    emptyBody: "Create the first quote or upload DXF files — a draft is created automatically.",
    noResults: "No quote matches the filters.",
    noFlags: "No flags",
    pendingOverrides: "{count} pending overrides",
  },
  create: {
    eyebrow: "Quote",
    title: "New quote",
    subtitle: "Quote header. Parts are added in the next step (file upload).",
    type: "Quote type",
    customer: "Customer",
    noCustomer: "No customer (fill in later)",
    currency: "Currency",
    currencyHelp: "PLN for Poland, EUR for every other country by default — editable.",
    fxRate: "EUR → PLN rate",
    fxRateHelp: "Rate tables are in EUR; the rate is stored on the quote and never changes by itself.",
    margin: "Margin (% of price)",
    marginHelp: "Default from the active rate version (or the customer class). Margin on price.",
    validityDays: "Validity (days)",
    leadTime: "Lead time",
    paymentTerms: "Payment terms",
    notes: "Internal notes",
    submit: "Create quote",
    cancel: "Cancel",
  },
  types: { fabrication: "Fabrication", welding_only: "Welding only" },
  header: {
    eyebrow: "Quote",
    version: "version {version}",
    created: "Created",
    sent: "Sent",
    rateVersion: "Rate version",
    noRateVersion: "pinned at the first pricing run",
    customer: "Customer",
    noCustomer: "— no customer —",
    currency: "Currency",
    fxRate: "EUR→PLN rate",
    margin: "Margin (%)",
    markup: "markup {markup}",
    validityDays: "Validity (days)",
    validUntil: "valid until {date}",
    leadTime: "Lead time",
    paymentTerms: "Payment terms",
    notes: "Internal notes",
    showOperationsOnPdf: "Show operations on the PDF",
    weldingSeparate: "Welding as a separate block",
    save: "Save header",
    saved: "Header saved, prices recalculated.",
    readOnly: "Read only — this quote belongs to another user.",
    locked: "This quote has been sent — header and parts are locked. Create a new version to change it.",
  },
  parts: {
    title: "Parts",
    columns: {
      thumbnail: "Drawing",
      name: "Part",
      material: "Material / thickness",
      qty: "Qty",
      unitCost: "Cost / pc",
      unitPrice: "Price / pc",
      batch: "Batch total",
      flags: "Flags",
    },
    empty: "No parts",
    emptyBody: "Upload DXF or PDF files or add a part manually.",
    uploadParts: "Upload parts",
    openPart: "Open part",
    breakdown: "Operation breakdown",
    hideBreakdown: "Hide operations",
    extras: "Extras",
    remove: "Remove from quote",
    removeConfirm: "Remove this item? The part is deleted with it.",
    moveUp: "Move up",
    moveDown: "Move down",
    unattached: "Parts outside the quote",
    addToQuote: "Add to quote",
    noGeometry: "no geometry",
    scrap: "Scrap %",
    scrapDefault: "default",
    itemNotes: "Item notes",
    thumbnailAlt: "Thumbnail of part {name}",
  },
  operations: {
    title: "Operations",
    columns: {
      operation: "Operation",
      driver: "Qty / unit",
      rate: "Rate",
      unitCost: "Cost / pc",
      setupShare: "incl. setup",
      batchCost: "Batch cost",
    },
    types: {
      laser_cut: "Laser cutting",
      subcontract_cutting: "Cutting — subcontracted",
      tube_cut: "Tube / profile cutting",
      material: "Material",
      bend: "Bending",
      roll: "Rolling",
      weld: "Welding",
      thread: "Threads",
      feature: "Hole features",
      machining: "Machining",
      finish_powder: "Powder coating",
      finish_zinc: "Zinc plating",
      finish_deburr: "Deburring",
      finish_other: "Finish — other",
      engrave: "Engraving",
      handling: "Handling",
      setup: "Setup",
      other: "Other",
    },
    labels: {
      laser_cut: "Laser cutting",
      subcontract_cutting: "Subcontracted cutting",
      material: "Material (sheet)",
      material_tube: "Material (profile)",
      bend: "Bend",
      bend_setup: "Setup — bending",
      roll: "Rolling",
      weld: "Weld seam",
      weld_setup: "Setup — welding",
      weld_handling: "Handling — welding",
      weld_min_order: "Minimum order — welding",
      thread: "Thread",
      machining: "Machining",
      engrave: "Engraving",
      tube_cut: "Profile cutting",
      handling: "Handling",
    },
    units: {
      m: "m",
      mm: "mm",
      pierce: "pierces",
      kg: "kg",
      bend: "bends",
      min: "min",
      m2: "m²",
      each: "pcs",
      part: "parts",
      lot: "lot",
    },
    placeholderRate: "placeholder rate",
    manual: "manual",
  },
  totals: {
    title: "Summary",
    byType: "By operation type",
    columns: { type: "Operation", cost: "Cost", price: "Price" },
    subtotalCost: "Total cost",
    subtotalPrice: "Net total price",
    margin: "Margin",
    marginAmount: "Margin amount",
    internalOnly: "Cost and margin are internal — never printed on the PDF.",
    inEur: "in EUR",
    fxNote: "Amounts in {currency} at rate {fx}.",
    preview: "Preview",
    previewBody: "Prices recomputed locally from your edits. Save to let the server confirm them.",
    pricedAt: "Priced {date}",
    notPriced: "Not priced yet — add parts or seams.",
    recalculate: "Recalculate",
    placeholderRates: "Placeholder rates [CONFIRM] were used — the admin must confirm them.",
  },
  flags: {
    title: "Feasibility flags",
    none: "No flags — everything within the machine limits.",
    red: "Blocking",
    amber: "Need confirmation",
    green: "Information",
    redExplanation: "A red flag blocks sending and cannot be overridden. Change the part (material, thickness, bends) or subcontract it.",
    confirm: "Confirm",
    confirmed: "Confirmed",
    requestOverride: "Request override",
    overrideRequested: "Override waiting for the admin's decision",
    overrideApproved: "Override approved",
    overrideRejected: "Override rejected — fix the part or request again",
    partScope: "Part: {name}",
    quoteScope: "Whole quote",
    dialogTitle: "Override request",
    dialogNote: "Justification for the admin",
    dialogNotePlaceholder: "Why we can do this despite the flag…",
    dialogSubmit: "Send request",
    dialogCancel: "Cancel",
    requestSent: "Override request sent. The quote waits for a decision.",
    confirmedToast: "Flag confirmed.",
  },
  overrides: {
    title: "Overrides",
    empty: "No overrides for this quote.",
    columns: {
      rule: "Rule",
      part: "Part",
      requestedBy: "Requested by",
      note: "Justification",
      status: "Status",
      decided: "Decision",
    },
    status: {
      pending: "Pending",
      approved: "Approved",
      rejected: "Rejected",
      confirmed: "Confirmed by sales",
    },
    confirmationNote: "confirmed by sales",
  },
  actions: {
    title: "Actions",
    upload: "Upload parts",
    duplicate: "New version",
    duplicateConfirm: "Create a new version of this quote (copy of parts and quantities, active rate version)?",
    duplicated: "New version created.",
    exportPdf: "PDF",
    exportPdfPl: "PDF (PL)",
    exportPdfEn: "PDF (EN)",
    withOperations: "with operations",
    send: "Send quote",
    sendConfirm: "Send the quote to the customer? The status becomes \"sent\".",
    sendBlocked: "Cannot send:",
    sent: "Quote e-mailed to the customer.",
    sentNoMail: "Quote marked as sent. PDF stored — e-mail sending is not configured, download the PDF and send it manually.",
    mailNotConfigured: "E-mail sending is off (no Microsoft Graph configuration) — \"Send\" stores the PDF and changes the status.",
    markWon: "Won",
    markLost: "Lost",
    decisionSaved: "Status saved.",
    recalculate: "Recalculate prices",
    recalculated: "Prices recalculated on the server.",
  },
  send: {
    reasons: {
      red_flags: "the quote has red flags",
      pending_override: "an override is waiting for the admin's decision",
      amber_unconfirmed: "amber flags need a confirmation or an approved override",
      no_customer: "no customer",
      no_customer_email: "the customer has no e-mail address",
      no_items: "no parts and no seams",
      not_priced: "the quote has not been priced yet",
      status: "the quote was already sent or decided",
    },
    localePl: "Polish",
    localeEn: "English",
    sendLocale: "Quote language",
  },
  welding: {
    title: "Seams",
    partsCount: "Customer parts",
    partsCountHelp: "For handling: a cost per supplied part.",
    columns: {
      label: "Seam",
      process: "Process",
      bead: "Bead a [mm]",
      length: "Length [mm]",
      pattern: "Pattern",
      beadLength: "Segment [mm]",
      pitch: "Pitch [mm]",
      sides: "Sides",
      qty: "Qty",
    },
    patterns: { full: "full", stitch: "stitch" },
    processes: { mig_mag: "MIG/MAG", tig: "TIG", laser: "Laser", mma: "MMA (stick)" },
    addSeam: "Add seam",
    removeSeam: "Remove",
    importFromParts: "Import from drawings",
    importedNone: "The parts have no marked seams.",
    imported: "Imported {count} seams.",
    empty: "No seams. Add a row or import the seams marked on the drawings.",
    save: "Save seams",
    saved: "Seams saved, prices recalculated.",
    blockTitle: "Welding",
    minOrderApplied: "Minimum order applied.",
    seamDefaultLabel: "Seam {n}",
  },
  extras: {
    title: "Extras — {name}",
    machining: "Machining",
    machiningMinutes: "Minutes per piece",
    features: "Hole features",
    featureCode: "Feature",
    featureCount: "Count",
    finish: "Finish",
    finishCode: "Finish",
    maskingMinutes: "Masking [min]",
    other: "Other line",
    otherLabel: "Label",
    otherCost: "Cost / pc [EUR]",
    handling: "Handling",
    handlingCost: "Cost / pc [EUR]",
    add: "Add",
    remove: "Remove",
    empty: "No extras — geometry-driven operations are priced automatically.",
    save: "Save extras",
    saved: "Extras saved, prices recalculated.",
    costEur: "Enter extra costs in EUR (the rate-table currency).",
    none: "none",
    summary: "{count} extras",
  },
  audit: {
    title: "Change history",
    empty: "No entries.",
    columns: { when: "When", who: "Who", action: "Event" },
    actions: {
      "quote.create": "quote created",
      "quote.update": "header changed",
      "quote.item.update": "item changed",
      "quote.item.remove": "item removed",
      "quote.item.add": "item added",
      "quote.item.reorder": "items reordered",
      "quote.welding.update": "seams changed",
      "quote.duplicate": "new version",
      "quote.reprice": "prices recalculated",
      "quote.send": "quote sent",
      "quote.status": "status changed",
      "override.request": "override requested",
      "override.confirm": "flag confirmed",
      "override.approve": "override approved",
      "override.reject": "override rejected",
    },
  },
  defaults: {
    // [CONFIRM] default payment terms text
    paymentTerms: "Payment by bank transfer within 14 days of the invoice date. Prices net, VAT according to applicable law.",
    // [CONFIRM] default lead time
    leadTime: "10–15 working days from order confirmation",
  },
  errors: {
    required: "Required.",
    invalid: "Invalid value.",
    tooLong: "Too long.",
    invalidNumber: "Invalid number.",
    invalidQty: "Quantity must be a whole number above zero.",
    invalidMargin: "Margin must be between 0 and 99.99 %.",
    invalidFx: "Invalid exchange rate.",
    invalidCurrency: "Pick PLN or EUR.",
    invalidType: "Pick a quote type.",
    invalidStatus: "Invalid status.",
    notFound: "Quote not found.",
    forbidden: "You are not allowed to change this quote.",
    locked: "The quote is locked (sent or decided).",
    noRates: "No active rate version — the admin must activate one.",
    pricing: "Pricing failed: {message}",
    cannotSend: "The quote does not meet the sending rules.",
    mail: "PDF stored, but the e-mail was not sent. Check the mail configuration.",
    generic: "Something went wrong. Try again.",
  },
};

export const quote: QuoteContent = {
  title: "Quote",
  builder: builderEn,
  customers: {
    eyebrow: "Customers",
    title: "Customers",
    subtitle: "Customer database: quote details, class and offer history.",
    newTitle: "New customer",
    newSubtitle: "The customer's country sets the default quote currency.",
    editEyebrow: "Customer",
    list: {
      search: "Search customers",
      searchPlaceholder: "Name, VAT id or e-mail…",
      newCustomer: "New customer",
      columns: {
        name: "Name",
        country: "Country",
        customerClass: "Class",
        vatId: "VAT id",
        email: "E-mail",
        quotes: "Quotes",
        lastQuote: "Last quote",
      },
      empty: "No customers",
      emptyBody: "Add the first customer to attach it to a quote.",
      noResults: "No customer matches the search.",
    },
    form: {
      sectionDetails: "Company",
      sectionContact: "Contact",
      sectionPreferences: "Preferences",
      name: "Name",
      vatId: "VAT id",
      vatIdHelp: "With the country prefix for EU companies, e.g. DE123456789.",
      country: "Country",
      countryGroupPreferred: "Frequent countries",
      countryGroupOther: "Other countries",
      address: "Address",
      email: "E-mail",
      phone: "Phone",
      customerClass: "Customer class",
      preferredLocale: "Quote language",
      preferredLocaleNone: "Default (by country)",
      preferredLocaleHelp: "Language of the quote PDF and customer e-mails.",
      notes: "Notes",
      currencyHint: "Default quote currency: {currency} (PLN for Poland, EUR for every other country).",
      create: "Create customer",
      save: "Save changes",
      created: "Customer created.",
      saved: "Changes saved.",
      deleteCustomer: "Delete customer",
      deleteConfirm: "Delete this customer? Quotes stay but lose the link.",
      deleted: "Customer deleted.",
      backToList: "Customer list",
    },
    classes: {
      standard: "Standard",
      key: "Key account",
      new: "New",
      distributor: "Distributor",
    },
    countries: {
      PL: "Poland",
      DE: "Germany",
      NL: "Netherlands",
      BE: "Belgium",
      CZ: "Czechia",
      SK: "Slovakia",
      AT: "Austria",
      FR: "France",
      IT: "Italy",
      ES: "Spain",
      GB: "United Kingdom",
      DK: "Denmark",
      SE: "Sweden",
      FI: "Finland",
      NO: "Norway",
      CH: "Switzerland",
      LT: "Lithuania",
      LV: "Latvia",
      EE: "Estonia",
      HU: "Hungary",
      RO: "Romania",
      UA: "Ukraine",
      LU: "Luxembourg",
      IE: "Ireland",
      PT: "Portugal",
      SI: "Slovenia",
      HR: "Croatia",
    },
    history: {
      title: "Quote history",
      empty: "This customer has no quotes yet.",
      columns: {
        number: "Number",
        version: "Version",
        type: "Type",
        status: "Status",
        date: "Date",
        total: "Total",
      },
      types: { fabrication: "Fabrication", welding_only: "Welding only" },
    },
    errors: {
      required: "Required.",
      tooLong: "Too long.",
      invalidEmail: "Invalid e-mail address.",
      invalidCountry: "Invalid country code (ISO 3166-1, e.g. DE).",
      invalidClass: "Pick a class from the list.",
      invalidLocale: "Pick a language from the list.",
      notFound: "Customer not found.",
      forbidden: "You are not allowed to do this.",
      generic: "The customer could not be saved. Try again.",
    },
  },
};
