/**
 * quote content (EN) — mirror of /content/quote.ts.
 * File path: /content/en/quote.ts
 */

import type { QuoteContent } from "@/content/quote";

export const quote: QuoteContent = {
  title: "Quote",
  customers: {
    eyebrow: "Customers",
    title: "Customers",
    subtitle: "Customer database: quote details, class and offer history.",
    newTitle: "New customer",
    newSubtitle: "The customer's country sets the default quote currency.",
    editEyebrow: "Customer",
    list: {
      search: "Search customers",
      searchPlaceholder: "Name, VAT id or e-mail…",
      newCustomer: "New customer",
      columns: {
        name: "Name",
        country: "Country",
        customerClass: "Class",
        vatId: "VAT id",
        email: "E-mail",
        quotes: "Quotes",
        lastQuote: "Last quote",
      },
      empty: "No customers",
      emptyBody: "Add the first customer to attach it to a quote.",
      noResults: "No customer matches the search.",
    },
    form: {
      sectionDetails: "Company",
      sectionContact: "Contact",
      sectionPreferences: "Preferences",
      name: "Name",
      vatId: "VAT id",
      vatIdHelp: "With the country prefix for EU companies, e.g. DE123456789.",
      country: "Country",
      address: "Address",
      email: "E-mail",
      phone: "Phone",
      customerClass: "Customer class",
      preferredLocale: "Quote language",
      preferredLocaleNone: "Default (by country)",
      preferredLocaleHelp: "Language of the quote PDF and customer e-mails.",
      notes: "Notes",
      currencyHint: "Default quote currency: {currency} (PLN for Poland, EUR for every other country).",
      create: "Create customer",
      save: "Save changes",
      created: "Customer created.",
      saved: "Changes saved.",
      deleteCustomer: "Delete customer",
      deleteConfirm: "Delete this customer? Quotes stay but lose the link.",
      deleted: "Customer deleted.",
      backToList: "Customer list",
    },
    classes: {
      standard: "Standard",
      key: "Key account",
      new: "New",
      distributor: "Distributor",
    },
    countries: {
      PL: "Poland",
      DE: "Germany",
      NL: "Netherlands",
      BE: "Belgium",
      CZ: "Czechia",
      SK: "Slovakia",
      AT: "Austria",
      FR: "France",
      IT: "Italy",
      ES: "Spain",
      GB: "United Kingdom",
      DK: "Denmark",
      SE: "Sweden",
      FI: "Finland",
      NO: "Norway",
      CH: "Switzerland",
      LT: "Lithuania",
      LV: "Latvia",
      EE: "Estonia",
      HU: "Hungary",
      RO: "Romania",
      UA: "Ukraine",
      LU: "Luxembourg",
      IE: "Ireland",
      PT: "Portugal",
      SI: "Slovenia",
      HR: "Croatia",
    },
    history: {
      title: "Quote history",
      empty: "This customer has no quotes yet.",
      columns: {
        number: "Number",
        version: "Version",
        type: "Type",
        status: "Status",
        date: "Date",
        total: "Total",
      },
      types: { fabrication: "Fabrication", welding_only: "Welding only" },
    },
    errors: {
      required: "Required.",
      tooLong: "Too long.",
      invalidEmail: "Invalid e-mail address.",
      invalidCountry: "Pick a country from the list.",
      invalidClass: "Pick a class from the list.",
      invalidLocale: "Pick a language from the list.",
      notFound: "Customer not found.",
      forbidden: "You are not allowed to do this.",
      generic: "The customer could not be saved. Try again.",
    },
  },
};
