/**
 * upload content (EN) — mirror of /content/upload.ts.
 * File path: /content/en/upload.ts
 */

import type { UploadContent } from "@/content/upload";

export const upload: UploadContent = {
  title: "Upload files",
  aiSuggestions: {
    heading: "Suggestions from the PDF",
    sourceAi: "suggested by AI",
    sourceHeuristic: "read from PDF",
    modelLabel: "Model: {model}",
    confidenceLabel: "Confidence",
    confidence: { low: "low", medium: "medium", high: "high" },
    fields: {
      partNumber: "Part number",
      material: "Material",
      materialFamily: "Material family",
      thicknessMm: "Thickness [mm]",
      quantity: "Quantity [pcs]",
      weightKg: "Weight [kg]",
      dimensionsMm: "Blank size [mm]",
      bends: "Bends",
      bendCount: "Number of bends",
      bendAngles: "Bend angles",
      bendDirections: "Bend directions",
      threads: "Threads",
      finish: "Finish",
      tolerances: "Tolerances",
      notes: "Notes",
    },
    directions: { up: "up", down: "down" },
    materialFamilies: {
      mild_steel: "mild steel",
      stainless: "stainless steel",
      aluminium: "aluminium",
      brass: "brass",
      copper: "copper",
    },
    finishCodes: {
      powder_coating: "powder coating",
      galvanised: "galvanised / zinc plated",
      anodised: "anodised",
      blasted: "blasted",
      brushed: "brushed",
      pickled_passivated: "pickled / passivated",
      painted: "painted",
      deburred: "deburred",
      none: "none (raw)",
    },
    ralLabel: "RAL {ral}",
    notes: {
      text: "{text}",
      hole: "Hole {callout}",
      hole_fit: "Hole {callout} — fit, machining",
      chamfer: "Chamfer {a}×{b}°",
      radii: "Radius callouts: {list}",
      angles_no_context: "Angles seen: {list} (no bend context)",
      other_materials: "Other material tokens: {list}",
      thread_repeated: "{size}: callout seen {seen}× — count not summed",
      ai_unavailable: "AI unavailable — showing the values read from the PDF.",
      pdf_too_large: "PDF too large for AI — only the text was analysed.",
      ai_value_dropped: "{field}: AI value “{value}” out of range — ignored",
    },
    accept: "Apply",
    acceptAll: "Apply all",
    dismiss: "Dismiss",
    dismissAll: "Dismiss all",
    matchesCurrent: "matches the current value",
    differsFromCurrent: "current: {current}",
    neverAutoApplied:
      "Suggestions are never applied automatically — each one needs your confirmation.",
    noApiKey: "No API key — showing the text extracted from the PDF.",
    extractedText: "Text from the PDF",
    noExtractedText: "The PDF has no text layer (scan or graphics only).",
    companionMatched: "PDF {pdf} matched to {dxf} by file name.",
    empty: "Nothing to suggest from this PDF.",
  },
  start: {
    eyebrow: "Upload files",
    title: "New quote from files",
    subtitle: "Create a draft quote and upload DXF flat patterns, PDF drawings or STEP models. Customer and commercial details come later in the quote builder.",
    newQuote: "Start a new quote",
    newQuoteHelp: "Creates a draft with the next SM-YYYY-NNNN number and opens its upload screen.",
    recentTitle: "Your drafts",
    recentEmpty: "You have no drafts yet. Start a new quote above.",
    continueQuote: "Continue",
    guideLink: "DXF export guide",
    noCustomer: "no customer",
    columns: { number: "Number", customer: "Customer", parts: "Parts", updated: "Updated", status: "Status" },
  },
  intake: {
    eyebrow: "File upload",
    title: "Quote {number}",
    subtitle: "Drag files in or pick them from disk. Every DXF becomes a part with a thumbnail and its triage result; a PDF with the same name attaches automatically.",
    backToQuote: "Back to the quote",
    openQuote: "Open the quote",
    addQuickPart: "Add a quick part",
    guideLink: "How do I export a DXF?",
    readOnly: "This quote is closed for editing — files can only be viewed.",
    dropzone: {
      title: "Drop files here",
      hint: "or",
      browse: "Choose files",
      formats: "DXF, PDF, STEP / STP — several at once",
      maxSize: "max. {mb} MB per file",
      dropHere: "Drop to upload",
      inputLabel: "Choose files to upload",
      queueLabel: "Upload queue",
    },
    status: {
      queued: "Queued",
      signing: "Preparing",
      uploading: "Uploading",
      analysing: "Analysing geometry",
      done: "Done",
      error: "Error",
    },
    results: {
      title: "Uploaded in this session",
      empty: "Uploaded files appear here with a thumbnail and their triage result.",
      openPart: "Open part",
      companionMatched: "PDF {pdf} matched to part {part}.",
      pdfWaiting: "PDF stored — it will attach to a DXF with the same name once you upload it.",
      pdfAttached: "PDF attached to part {part}.",
      restored: "Earlier annotations for this file were restored.",
      stepManual: "STEP stored — geometry is not unfolded. Enter the dimensions as a quick part.",
      multiPart: "The file holds {count} parts — the largest is priced.",
      healingLabel: "Healing",
      suggestionsAi: "AI suggestions from the PDF",
      suggestionsHeuristic: "values read from the PDF",
      remove: "Remove from list",
      retry: "Retry",
      guideLink: "See the export guide",
    },
    parts: {
      title: "Parts in this quote",
      count: "{count} parts",
      empty: "No parts yet. Upload a DXF or add a quick part.",
      columns: {
        thumbnail: "Preview",
        name: "Name",
        source: "Source",
        material: "Material / thickness",
        qty: "Qty",
        triage: "Triage",
        flags: "Flags",
        actions: "Actions",
      },
      noMaterial: "not set",
      noTriage: "—",
      pdfAttached: "PDF",
      edit: "Edit",
      delete: "Delete",
      deleteConfirm: "Remove this part from the quote?",
      deleted: "Part deleted.",
    },
    sources: {
      dxf: "DXF",
      pdf: "PDF",
      step: "STEP",
      manual: "Manual",
      welding_drawing: "Welding drawing",
    },
  },
  quickPart: {
    title: "Quick part",
    replaceTitle: "Enter the part manually",
    intro: "A rectangle L × W with holes and bends — when the file is unusable or the customer gave dimensions only. The part is flagged as manual geometry.",
    name: "Part name",
    length: "Length L [mm]",
    width: "Width W [mm]",
    thickness: "Thickness [mm]",
    material: "Material",
    materialNone: "— choose later —",
    holes: "Holes",
    holeDiameter: "Diameter [mm]",
    holeCount: "Count",
    addHole: "Add holes",
    removeHole: "Remove hole row",
    bends: "Bends",
    bendLength: "Length [mm]",
    bendAngle: "Angle [°]",
    bendCount: "Count",
    addBend: "Add bends",
    removeBend: "Remove bend row",
    rolled: "Rolling",
    rolledToggle: "The part is rolled",
    rollRadius: "Radius [mm]",
    rollAxisLength: "Axis length [mm]",
    submit: "Create part",
    cancel: "Cancel",
    created: "Part created.",
    manualBadge: "Manual geometry",
  },
  part: {
    eyebrow: "Part",
    backToQuote: "Back to the quote",
    downloadOriginal: "Download original",
    downloadPdf: "Download PDF",
    rename: "Rename",
    nameLabel: "Part name",
    saveName: "Save name",
    readOnlyNotice: "View only — this quote is no longer editable or you have no write access to it.",
    noGeometryTitle: "No geometry",
    noGeometryBody: "This file has no flat pattern to show.",
    stepBody: "STEP files are not unfolded in this version. Enter the flat-pattern dimensions as a quick part — the name is already filled in.",
    enterQuickPart: "Enter as a quick part",
    saved: "Annotations saved.",
    saveError: "Saving the annotations failed.",
    saving: "Saving…",
    viewerLabel: "Flat pattern viewer",
    panels: {
      material: "Material and thickness",
      triage: "File triage",
      measures: "Measures",
      holes: "Holes",
      bends: "Bends",
      welds: "Welds",
      roll: "Rolling",
      ai: "PDF and suggestions",
      flags: "Feasibility flags",
      quantity: "Quantity and price",
      actions: "Actions",
      pdfText: "Text from the PDF",
    },
    material: {
      code: "Material",
      thickness: "Thickness [mm]",
      none: "— not set —",
      limitHint: "Our laser cuts {family} up to {limitMm} mm ({machine}); thicker goes to a subcontractor.",
      noLimit: "No thickness limit for this material in the machine park.",
      noRates: "No active rate version — the material list is empty. Activate one in Admin → Rates.",
      save: "Save material",
      unknownCode: "Code not in the rate tables — pricing will flag a missing material.",
    },
    measures: {
      cutLength: "Cut length",
      outerLength: "Outer contour",
      holesLength: "Holes",
      pierces: "Pierces",
      bbox: "Bounding box",
      blank: "Blank",
      netArea: "Net area",
      mass: "Mass",
      smallestContour: "Smallest contour",
      slowContours: "Slow contours",
      weldLength: "Weld length",
      engraveLength: "Engraving length",
      bendLines: "Bend lines",
      partCount: "Parts in file",
      unknown: "— set thickness —",
      blankMargin: "margin {marginMm} mm",
    },
    holes: {
      diameter: "Ø [mm]",
      count: "Count",
      thread: "Thread",
      suggested: "suggested",
      confirmed: "confirmed",
      confirm: "Confirm thread",
      noThread: "no thread",
      auto: "automatic",
      empty: "No holes.",
      matchedBy: { minor_diameter: "minor diameter", tap_drill: "tap drill" },
      circular: "circular",
      nonCircular: "non-circular",
    },
    bends: {
      direction: "Direction",
      length: "Length [mm]",
      angle: "Angle [°]",
      radius: "Radius [mm]",
      source: "Source",
      up: "up",
      down: "down",
      unknown: "unknown",
      empty: "No bend lines. Draw them in the viewer or answer in the triage panel.",
      save: "Save",
      sources: { layer: "layer", drawn: "drawn", candidate: "candidate" },
      radiusDefault: "= thickness",
    },
    welds: {
      process: "Process",
      bead: "Bead [mm]",
      pattern: "Pattern",
      sides: "Sides",
      length: "Length [mm]",
      effective: "Effective [mm]",
      empty: "No weld seams. Select an edge in the viewer and use the weld tool.",
      patterns: { full: "full", stitch: "stitch" },
      stitchInfo: "{bead}/{pitch} mm",
    },
    roll: {
      radius: "Radius",
      axis: "Axis",
      arcAngle: "Arc angle",
      axisLength: "Axis length",
      developedWidth: "Developed width",
      cone: "Cone",
      coneInfo: "R {inner}–{outer} mm, {sweep}°",
      none: "The part is not rolled. Mark rolling in the viewer.",
      axes: { x: "X", y: "Y" },
    },
    ai: {
      runPrefill: "Read the PDF",
      running: "Reading…",
      noPdf: "No PDF attached. Upload a drawing with the same name as the DXF on the upload screen.",
      attachPdfHint: "From the PDF we read thickness, material, bends, threads, finish and quantity.",
      showText: "Show PDF text",
      hideText: "Hide PDF text",
      extractText: "Extract text",
      prefillDone: "Suggestions refreshed.",
      pending: "{count} suggestions to confirm",
      allApplied: "Every suggestion matches the part or was dismissed.",
      applied: "Suggestion applied.",
      dismissed: "Dismissed.",
    },
    flags: {
      empty: "No flags — the last pricing run raised nothing.",
      notPriced: "The part has not been priced yet. Flags appear once the quote is re-priced.",
      hint: "A red flag blocks sending; an amber one needs a confirmation or an override.",
    },
    quantity: {
      qty: "Quantity [pcs]",
      unitCost: "Cost / pc",
      unitPrice: "Price / pc",
      batchPrice: "Batch price",
      notPriced: "not priced",
      inCurrency: "in {currency}",
    },
    actions: {
      reanalyse: "Re-analyse geometry",
      tolerance: "Join tolerance [mm]",
      toleranceHelp: "0.01–0.5 mm. A larger tolerance closes gaps between lines but may merge neighbouring edges.",
      exportDxf: "Export annotated DXF",
      delete: "Delete part",
      deleteConfirm: "Delete the part and its quote line?",
      reanalysed: "Geometry re-analysed.",
      reanalysedCached: "Geometry taken from the cache (same file).",
    },
    triage: {
      reasons: "Reasons",
      healing: "Healing",
      dropped: "Dropped",
      confirmUnits: "Dimensions are in mm — confirm",
      calibrateHint: "Not sure? Calibrate in the viewer: click two points and type the real distance.",
      candidatesQuestion: "These {count} lines are:",
      bendUp: "Bend up",
      bendDown: "Bend down",
      ignore: "Ignore",
      cut: "Cut",
      tagHint: "The answer applies to all lines at once. To tag them individually, select a line in the viewer and use the tag tool.",
      formingQuestion: "Is this part bent or rolled?",
      flat: "Flat",
      bent: "Bent",
      rolled: "Rolled",
      pickView: "Pick the view that is the flat part",
      pickViewHelp: "In the viewer, lasso the flat-pattern view, then use clean-up “keep largest contour and its holes”. The rest of the sheet is ignored.",
      joinTolerance: "Join tolerance [mm]",
      joinAndRetry: "Join and re-analyse",
      quickPart: "Enter as a quick part",
      answered: "Answer saved.",
    },
  },
  errors: {
    extension: "Unsupported file type. Allowed: DXF, PDF, STEP / STP.",
    size: "The file is too large — the limit is 25 MB.",
    dwg: "DWG is not supported. Save the file as DXF (AutoCAD: Save As → DXF) and upload it again.",
    empty: "The file is empty.",
    binary_dxf: "This is a binary DXF. Save it as ASCII DXF (AutoCAD 2018 or R12) and upload it again.",
    unknown_type: "The file content was not recognised — it is not a DXF, PDF or STEP.",
    type_mismatch: "The file content does not match its extension.",
    invalid_body: "Invalid request.",
    invalid_path: "Invalid file path.",
    not_uploaded: "The file did not reach storage. Try again.",
    conflict: "This file was already registered. Upload it again.",
    network: "Connection error. Check the network and try again.",
    upload_failed: "The upload failed.",
    unauthenticated: "Your session expired — sign in again.",
    forbidden: "You cannot edit this quote.",
    not_found: "Quote or part not found.",
    locked: "This quote is closed for editing.",
    invalid_id: "Invalid identifier.",
    validation: "Check the values you entered.",
    no_geometry: "This part has no geometry to re-analyse.",
    no_rates: "No active rate version.",
    bend_not_found: "That bend was not found.",
    no_bends: "The part has no bend lines to apply angles to.",
    nothing_to_apply: "This suggestion has nothing to apply.",
    no_pdf: "The part has no PDF attached.",
    no_item: "The part has no quote line.",
    generic: "Something went wrong. Try again.",
  },
};
