/**
 * upload content (EN) — mirror of /content/upload.ts.
 * File path: /content/en/upload.ts
 */

import type { UploadContent } from "@/content/upload";

export const upload: UploadContent = {
  title: "upload",
  aiSuggestions: {
    heading: "Suggestions from the PDF",
    sourceAi: "suggested by AI",
    sourceHeuristic: "read from PDF",
    modelLabel: "Model: {model}",
    confidenceLabel: "Confidence",
    confidence: { low: "low", medium: "medium", high: "high" },
    fields: {
      partNumber: "Part number",
      material: "Material",
      materialFamily: "Material family",
      thicknessMm: "Thickness [mm]",
      quantity: "Quantity [pcs]",
      weightKg: "Weight [kg]",
      dimensionsMm: "Blank size [mm]",
      bends: "Bends",
      bendCount: "Number of bends",
      bendAngles: "Bend angles",
      bendDirections: "Bend directions",
      threads: "Threads",
      finish: "Finish",
      tolerances: "Tolerances",
      notes: "Notes",
    },
    directions: { up: "up", down: "down" },
    materialFamilies: {
      mild_steel: "mild steel",
      stainless: "stainless steel",
      aluminium: "aluminium",
      brass: "brass",
      copper: "copper",
    },
    finishCodes: {
      powder_coating: "powder coating",
      galvanised: "galvanised / zinc plated",
      anodised: "anodised",
      blasted: "blasted",
      brushed: "brushed",
      pickled_passivated: "pickled / passivated",
      painted: "painted",
      deburred: "deburred",
      none: "none (raw)",
    },
    ralLabel: "RAL {ral}",
    notes: {
      text: "{text}",
      hole: "Hole {callout}",
      hole_fit: "Hole {callout} — fit, machining",
      chamfer: "Chamfer {a}×{b}°",
      radii: "Radius callouts: {list}",
      angles_no_context: "Angles seen: {list} (no bend context)",
      other_materials: "Other material tokens: {list}",
      thread_repeated: "{size}: callout seen {seen}× — count not summed",
      ai_unavailable: "AI unavailable — showing the values read from the PDF.",
      pdf_too_large: "PDF too large for AI — only the text was analysed.",
      ai_value_dropped: "{field}: AI value “{value}” out of range — ignored",
    },
    accept: "Apply",
    acceptAll: "Apply all",
    dismiss: "Dismiss",
    dismissAll: "Dismiss all",
    matchesCurrent: "matches the current value",
    differsFromCurrent: "current: {current}",
    neverAutoApplied:
      "Suggestions are never applied automatically — each one needs your confirmation.",
    noApiKey: "No API key — showing the text extracted from the PDF.",
    extractedText: "Text from the PDF",
    noExtractedText: "The PDF has no text layer (scan or graphics only).",
    companionMatched: "PDF {pdf} matched to {dxf} by file name.",
    empty: "Nothing to suggest from this PDF.",
  },
};
