/**
 * Viewer content (EN) — mirror of /content/viewer.ts.
 * File path: /content/en/viewer.ts
 */

import type { ViewerContent } from "@/content/viewer";

export const viewer: ViewerContent = {
  title: "Drawing viewer",
  canvasLabel: "Part drawing — editor canvas",
  toolbarLabel: "Editor tools",
  layersLabel: "Layers",
  readOnly: "View only",
  tools: {
    select: "Select",
    tag: "Tag",
    bend: "Bend line",
    weld: "Weld seam",
    roll: "Rolling",
    calibrate: "Calibrate",
    cleanup: "Clean-up",
    export: "Export DXF",
    fit: "Fit",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    reset: "100 %",
    cancel: "Cancel",
    delete: "Delete selection",
  },
  tooltips: {
    select: "Select: click, Shift+click adds, drag to lasso",
    tag: "Give the selected entities a role: cut, bend, weld, engrave, ignore",
    bend: "Draw a bend line with two clicks snapped to the outline",
    weld: "Add a weld seam on the selected edges or between two points",
    roll: "Roll the whole part: radius, axis, arc angle",
    calibrate: "Calibrate units: two points and the real distance",
    cleanup: "Clean-up: keep largest contour, delete, ignore, join, mirror, split",
    export: "Download the DXF with production layers",
    fit: "Fit the part into the view",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    reset: "View 1:1 (100 %)",
    cancel: "Cancel the current tool",
    delete: "Remove the selected entities from the quote",
  },
  layers: {
    cut: "Cut",
    holes: "Holes",
    bendUp: "Bend up",
    bendDown: "Bend down",
    weld: "Welds",
    engrave: "Engrave",
    ignored: "Ignored",
    candidates: "Candidates",
    grid: "Grid",
    snap: "Snap",
  },
  roles: {
    cut: "Cut",
    hole: "Hole",
    bend_up: "Bend up",
    bend_down: "Bend down",
    weld: "Weld",
    engrave: "Engrave",
    ignore: "Ignore",
    unknown: "Candidate",
  },
  readout: {
    x: "X",
    y: "Y",
    zoom: "Zoom",
    outside: "outside the drawing",
    selection: "{count} entities · {length} mm",
    noSelection: "Nothing selected",
    entities: "{count} entities",
    gridStep: "Grid {step} mm",
    focused: "Focused {index}/{count}: {role}",
  },
  measures: {
    title: "Measures",
    cutLength: "Cut length",
    pierces: "Pierces",
    bends: "Bends",
    weldLength: "Welds (effective)",
    bbox: "Bounding box",
    mass: "Mass",
    unknown: "—",
  },
  hints: {
    select: "Click an entity, Shift+click adds to the selection, drag to lasso.",
    tag: "Select entities, then pick a role.",
    bendFirst: "Click the first point of the bend line.",
    bendSecond: "Click the second point — snaps to endpoints, midpoints and perpendicular to edges.",
    weldEntities: "Click the edges that form the seam (Shift+click adds), then fill in the form.",
    weldPoints: "Click the start and the end of the seam.",
    calibrateFirst: "Click the first point of a known dimension.",
    calibrateSecond: "Click the second point, then type the real distance.",
    cleanup: "Pick a clean-up operation. Selection operations need selected entities.",
    pan: "Pan: middle button or Space + drag.",
    zoom: "Zoom: mouse wheel, + / −, F fits.",
    shiftClick: "Shift+click adds to the selection.",
    lasso: "Dragging selects entities fully inside the rectangle.",
    cancel: "Esc cancels the tool.",
    deleteKey: "Delete removes the selection from the quote.",
    arrows: "Arrow keys pan the view (Shift: faster).",
    cycle: "step through the entities.",
    enterSelect: "selects the focused entity (Shift: adds).",
    enterPick: "picks both ends of the focused entity as points.",
    selectAll: "selects every visible entity.",
  },
  point: {
    title: "Type a point",
    x: "X",
    y: "Y",
    add: "Add point",
    clear: "Clear points",
  },
  snapKinds: {
    endpoint: "endpoint",
    midpoint: "midpoint",
    center: "circle centre",
    perpendicular: "perpendicular",
  },
  tag: {
    title: "Tag selection",
    selection: "{count} selected",
    none: "Select entities on the drawing first.",
    apply: "Apply",
    clearOverride: "Clear tag",
  },
  bend: {
    title: "Bend",
    angle: "Angle",
    radius: "Inside radius",
    direction: "Direction",
    up: "Up",
    down: "Down",
    dieV: "Die V opening",
    dieVHelp: "Optional — default 8 × thickness",
    length: "Length",
    add: "Add bend line",
    drawn: "Drawn bend lines",
    empty: "No drawn bend lines.",
    remove: "Remove",
    picked: "Points",
  },
  weld: {
    title: "Weld seam",
    mode: "Pick by",
    modeEntities: "Edges",
    modePoints: "Two points",
    process: "Process",
    processes: { mig_mag: "MIG/MAG", tig: "TIG", laser: "Laser", mma: "MMA (stick)" },
    bead: "Bead size",
    pattern: "Pattern",
    full: "Full",
    stitch: "Stitch",
    beadLength: "Bead length",
    pitch: "Pitch",
    sides: "Sides",
    sidesOne: "1 side",
    sidesTwo: "2 sides",
    length: "Geometric length",
    effective: "Effective length",
    add: "Add weld",
    list: "Welds",
    empty: "No welds.",
    remove: "Remove",
    needSelection: "Select edges or pick two points.",
    pitchRequired: "Pitch must be greater than zero.",
  },
  roll: {
    title: "Roll the part",
    hint: "Rolling applies to the whole part. The roll axis is the straight dimension, the developed width the curved one.",
    inputMode: "Enter",
    radius: "Radius",
    diameter: "Diameter",
    axis: "Roll axis",
    axisX: "X",
    axisY: "Y",
    arcAngle: "Arc angle",
    axisLength: "Axis length",
    developedWidth: "Developed width",
    coneDetected: "Cone development detected (annular sector)",
    coneNone: "The outline is not an annular sector — values from the bounding box.",
    coneInner: "Inner radius",
    coneOuter: "Outer radius",
    coneSweep: "Sector angle",
    apply: "Save rolling",
    clear: "Remove rolling",
    current: "Rolling: R {radius} mm, axis {axis}, {angle}°",
    radiusRequired: "Enter a radius or diameter greater than zero.",
  },
  calibrate: {
    title: "Calibrate units",
    measured: "Measured",
    real: "Real distance",
    factor: "Factor",
    resultBbox: "Bounding box after calibration",
    apply: "Apply scale",
    current: "Scale: × {factor}",
    reset: "Remove scale",
    none: "Not calibrated (× 1)",
  },
  cleanup: {
    title: "Clean-up",
    keepLargest: "Keep largest contour and holes",
    keepLargestHelp: "Removes everything except the outer contour, its holes and the lines inside it from the quote.",
    deleteSelection: "Delete selection",
    ignoreSelection: "Ignore selection",
    join: "Join within tolerance",
    joinTolerance: "Tolerance",
    joinApply: "Join",
    joinHelp: "Joins endpoints within the tolerance (0.01–0.5 mm); re-analysed on the server.",
    mirror: "Mirror (X)",
    mirrorOn: "Part is mirrored",
    split: "Split into parts",
    splitHelp: "Every closed outer contour becomes a separate part.",
    restoreDeleted: "Restore deleted",
    deletedCount: "{count} deleted",
    needSelection: "Needs a selection.",
  },
  export: { label: "Export DXF", tooltip: "Download the DXF with CUT, HOLES, BEND_UP, BEND_DOWN, WELD, ENGRAVE, IGNORE layers" },
  units: { mm: "mm", deg: "°", kg: "kg", percent: "%" },
  legend: {
    title: "Shortcuts",
    shiftClick: "Shift + click",
    spaceDrag: "Space + drag",
    wheel: "Wheel",
    lasso: "Drag",
    arrows: "Arrows",
  },
};
